####
#  generate all attributes  (from the on-chain base64-encoded blobs)
#
#   $ ruby ./attributes

$LOAD_PATH.unshift( "../../pixelart/pixelart/lib" )
require 'pixelart'



attributes = {

###########
#  0) 1/1
"1/1" => {
  #  0.0  Zombie
  "Zombie" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAh0lEQVRIiWOsWZDxn4GGgIUUxS0JM+DsmgUZ1LWgJWEGiqHofFyAiRzDGRggPkD2EdkW4HMpMZYQ5QNKAF4LiAlnQr4YWB+MWjBqwagFoxYMFgseXHjD8ODCG4JiZFuwZMIahgUT1uAVw1dkE6yTaxZkMCRceMOgQEAMFyAqDhQMRPCK4atwACEdPGWTgOCqAAAAAElFTkSuQmCC",
  #  0.1  Cline
  "Cline" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA50lEQVRIiWP8+mDufwYaAhZSFHMrJMPZXx/Mpa4F3ArJDH9OIAxlUUgmyhImcgxnYGBg+HNiLoqPyLYAm+GkWEIwiCq9BRlqm0vwyuMDeH3Qko3bYGLVofigJbuEoWZqD5x//ckXoizAZiHMHIwgQnaNpgwPSYZiAyhBhOx6SgCyOYz4cjK+FIQMWCxw5wmi8gElYNSCUQuGgAUES1MWC8JlPj5A0AcxlvwMMZb8DAwMDPBcjU2MbAuybVgZsm1Y8Yrhq3gIBpFl9xsUl/45MRcebESVU4QUYDMEXYzFIpnhzwkVrA0BANUjV+34xSZ7AAAAAElFTkSuQmCC",
  #  0.2  Pauly Devil
  "Pauly Devil" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA7UlEQVRIiWOsWrjnPwMRoC3eBUOsauEegvpYcEmcyw5gMJq6AW64g4MDVkthliCrRwZMpBh+4MABOGZgYGBwcHCA+8xo6gaGc9kBxFmA7EJkw/8zMMAxNkuwAZwWYDMcGRBrCVYLdnz5gtdwXJbs+PKFeB8QMhybJdgAXguoAUYtIN0CXLmWGIAtueL0Ab6UQYr6oRUHBw4cwAimoeWDEWyB5gbMohibGFkW6E5xYGB58oegGC6As06GgT8XvjDcmHMGr9h/BgYGRhz6Cfrg+pwzDBpowYFNDBdgxNZsgZVHxFQ4DAwI18P0IDdnAJYVferUw6ZVAAAAAElFTkSuQmCC",
  #  0.3  Deal With It Devil
  "Deal With It Devil" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAvElEQVRIie2VMQ7DIAxFf6qOHKjK0DkHYq5QZu7TzBlQDsROl4IssE2qthtfQkgf6z8wg6fVuYQ/6iIdBO8b7+FcWWfqRUDwHrO1TXgCyqohs7UsRHwBF07FQTh1W8SFc5CPWkQhizHqDRdjxHARQPv/jFEF0PP630RALt464VlbjGy4CviVBmAABmAATujKmXSQTF8Cui849gAAzdChvjbdWMD6Lj72gNt9LuF5r31NbIsyhAtJAFD5WhtfS7dS19hlVDkAAAAASUVORK5CYII=",
  #  0.4  Marc 1/1 1
  "Marc 1" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAnklEQVRIiWOsWrjnPwMNAQspitviXeDsqoV7qGtBW7wLw58TcxEaLVyIsoSJHMMZGBgY/pyYi+Ijsi3AZjgplhDlA0oAXgvwuR4GCPliYH0wasGoBaMWjFpAJwuw1mjIpSOLRTJFFhD0wYlDxxgYGBgwim1kcXxFNlYLYHXtiUPHGCzsrOCGw2h0cXwAZ6VftXAPVkMg/OtoDQDcwQgAz/JJ+SK6cfMAAAAASUVORK5CYII=",
  #  0.5  Gold
  "Gold" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAkElEQVRIiWOsWrjnPwMNAQspitviXeDsqoV7qGtBW7wLw58TKgiNFi5EWcJEjuEMDAwMf06ooPiIbAuwGU6KJUT5gBKA1wJ8rocBQr4YWB+MWjBqwagFoxYMFgtOXv3JcPLqT4JiZFtg4NzAYJ38GK/Y1wdzcRbZBC1gf9GOUSegi7G/aMepnypxwGJxB6ccADAROgGZvaUJAAAAAElFTkSuQmCC",
  #  0.6  Marcdonalds
  "Marcdonalds" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA2klEQVRIiWOsWrjnPwMNAQspitviXeDsqoV7qGtBW7wLw58TcxEaLVyIsoSJHMMZGBgY/pyYi+IjXICRUBycWNSD14AnD+8yhNROxymP1wfIhu+p2YFCw4CMvDLDmuZM8ixANtylxQOFJhbgjeQnD+8yMDAwMDDeZ2R48vAuCk0swIgDQmGObLmMvDKcjSseMHxgEVcCZ2NLPVgNsUjGKUdUHFACRi0YtWDUgsFgwa1HLxluPXpJUIxsC9T1TRm0wqrwiuGr3Qha8P/9I4wCD5sYLkCVOMBXmgIAIlRjTj36ZhgAAAAASUVORK5CYII=",
  #  0.7  Marc 1/1 2
  "Marc 2" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAhUlEQVRIiWOsWrjnPwMNAQspitviXeDsqoV7qGtBW7wLQ6G9HAqfGEuYyDGcgYGBodBeDsVHZFuAzXBSLCHKB5QAvBbgcz0MEPLFwPpg1IJRC0YtGLVgsFjw7PkjhmfPHxEUI9sCKWEOhpW38IvhK7IJ18lsYgyF9kSI4QBUiYP+g7iDCwCyxCq6BxfTLAAAAABJRU5ErkJggg==",
  #  0.8  Devil
  "Devil" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAu0lEQVRIiWOsWrjnPwMNARMuiXPZARhibfEucEyMepwWnMsOYDCaugHD8P8MDHCMbonR1A1YLcHpA2yGIwNslmADBIMIm+HYLCEpiJAt8eDhwetCDx4enIbjtAA5/Ld/+YLXAmR59HjDaQFM8Q4ChsPAji9fsBqO1wJqgVELRi0YtWDUAmpY4MnDw+CJVmRjE8MFWAgp2P7lCwMjAbH/DAwMjPEuDFUL92DoJyqIsNVoxDZFqBIH6D5EBgDKxUD/QeS5OAAAAABJRU5ErkJggg==",
  #  0.9  Marc 1/1 3
  "Marc 3" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAmklEQVRIiWNsamj4z0BDwEKK4rqGBji7CYlNFQvqGhoY/pyYi9BokUyUJUzkGM7AwMDw58RcFB+RbQE2w0mxhCgfUALwWoDP9TBAyBcD64NRC0YtGLVg1AIIIFjhsFgk09aCa6vaGBgYGBjU5MSxWvjnxFy8jiAYROr6pgxaYVV41eArsgla8P/9I5Q6ARcbFyCpVYHLYHxBBADPLTvrk4j6EQAAAABJRU5ErkJggg==",
  #  0.10  Madlad Marc
  "Madlad Marc" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAxUlEQVRIie2WOw7CMAyGf9Moh2BuzsG1GBipxJ2Y4Bph5gRMIchMDUXNGyoUCS95yp//KLJNLCVjQRMll8kYN2cpvwsgY2D1ZK1MFmRV4xwArH5XVA3wOS+BZCn4xKKAWPSjpVT8VsEf0Bgg8JMaUrA4IJD4GlJQCxCqbL8YYPXcmVBIJsFsQNczmNlBhAKYGV2fV8rzKhqRi3gcicidx1J2EjCc77PneFwI+1O6XAIA+dqW4Xhz8+06XNgP1xdkt5HeJuAJE6VJouMMr1YAAAAASUVORK5CYII=",
  #  0.11  Chad
  "Chad" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA9ElEQVRIibWWMRKDIBBFP2Qrm9wkNZMil8kNPIg38DIpMtS5SRqrzZgKQwQWFPkzjsrAfwsri8oyz2go7R4MUbazIVquUpEbOE8DFBEsc9Kc7fgbKPT1pf2XeRqi0a3NAYDtWDQTvW5YQ2LmWyABIAapUdLF5SQVvRPbUcxHdAY+pFYiAABOl3dbQC2kCFADKQbshWwC7IFoALDMUF3fBLLMoBXkb4laQIIcHA2JJnkrRKpdya/oKEi2ZH5e56y5tExRgB8JmXsWAKQLY3aj2ccTAIKy7bdLVTeZZGdibtfF3N3X7ZKU9NsiHZe+XA5U1wcHzxdJ2X9o15zyFAAAAABJRU5ErkJggg==",
  #  0.12  Ape
  "Ape" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAm0lEQVRIiWNsKQj5z0BDwEKK4poJa+DsloIQovQwkWK4iYoAHCNbRrEFMMORAbGWELQAm+GkWEJ0EJEL8FqAz/UwQMgXA+uDUQtGLRi1YIhYQFSFc+bOBwwxQmUU0RYE+LgwBOCR37BlD179BIPoybM3DE+evSEoRrYFDmY6DDNWHcArhq/IJmjBnScvMCp4bGK4AFVSEbZEAAMAxrU57b9prfAAAAAASUVORK5CYII=",
  #  0.13  Claudia Bot
  "Claudia Bot" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAzElEQVRIie2VIQ7DIBSGf5YpLoLbHUgqa6u5Q3Gdbh29Q/Ussgl3qOMitUwsI1nCoLB1M/0V5L383/t5AtJNs8OOOuc0D6Ly526avwsYRAVjjL9zzjdBTiXmAGCMeUlUDAiZ50A2JfhEUUBs+qdSKf6b4AAcgAPwA4Bbx00msb7kf8A5LzZPAghtoZQCYyxYt9aC0BZuHdE3C663Sx4AABhjqOs6WNNaQynlISHtvuS3CfpmwSAez6C1DvZYayGlLF+yW0cQ2kYnTC35DtEFTyYL0CuvAAAAAElFTkSuQmCC",
  #  0.14  Marc 1/1 4
  "Marc 4" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAABCElEQVRIiWOsWrjnPwMNAQspitviXeDsqoV7qGtBW7wLw58TcxEaLVyIsoSJHMMZGBgY/pyYi+Ijsi3AZjgplhAMIjHzJQxS+fjlybZgzrQXDCw8KoTcwDBn2h2GlCwJrHJExQElAK8PXp2MYRAzX4Liiz9f7qAawKPC8O/rDYY50yDsP1/uMLDwqDAkxH0hbAEDAwPDs4k/GaTy76DwUcFVBhaLFgYRnRqGP1ALYYYTZQF2QzFBWqkDw6zuAwwMaHFG1ThIK3XAEKN6JCMHD00sQAejFoxaQAcLbj16yXDr0UuCYmRboK5vyqAVVoVXDF/FQ9CC/+8fYdRo2MRwAarEAYtFMk45ALM4YO85i9nLAAAAAElFTkSuQmCC",
  #  0.15  Bot
  "Bot" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAjUlEQVRIie2VPQrAIAyFY+nBzOp9XCV4KNd4s3YolRaq8aeliw+EyJN8eQ6qPNEGH2ptOeyIUu0v9SsARwTMnPaIWAVZepoDADDzLVE34Kl5C6QqwYiKgNL0p6QU/yaYgAmYgAk4JH44WuusF2MUAWICpVR2hRDGATUqPdniFVlrs54xRoSLgJomiJj1dkvTLu2TuhJBAAAAAElFTkSuQmCC",
  #  0.16  Marc 1/1 5
  "Marc 5" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAmklEQVRIiWNsamj4z0BDwEKK4rqGBji7CYlNFQvqGhoY/pyYi9BokUyUJUzkGM7AwMDw58RcFB+RbQE2w0mxhCgfUALwWoDP9TBAyBcD64NRC0YtGLVg1AISLNB5sZwoMWyAYI1mcGYxRJEEfjFcgKAP/lz4wnAl5wBeMXxFNkELrqRkMmhscCEohgsQFQdXJCLxirFYJOPUCwB3mT/fJRWPKQAAAABJRU5ErkJggg==",
  #  0.17  Marc 1/1 6
  "Marc 6" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAzklEQVRIiWOsWrjnPwMRoC3eBUOsauEegvpYiDXcwcEBqzghS5hIMfzAgQNwzMDAwODg4IDVZ0RbgG74nxNz4ZhYS3BagM1wZECsJVgtIGQ4KZbgDSJ8hmOzBBsgGMmUglELSLcAV64lBmBLSTh9gC9lkKJ+aMXBgQMHMIJpaPlgBFug82I5UWLYAMEq0+DMYogiCfxiuABBH/y58IXhSs4BgmJkW3AlJZNBY4MLXjF8dQaGBVUL98AzDNxAiUhMi7GIOTg4MBw4cAClpQEADvN5XvEbV8YAAAAASUVORK5CYII=",
  #  0.18  Alien
  "Alien" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAk0lEQVRIiWNsamj4z0BDwEKK4rqGBji7CYlNFQvqGhoYTvz5A+dbsLAQZQkTOYYzMDAwnPjzB8VHZFuAzXBSLCHKB5QAvBbgcz0MEPLFwPpg1IJRC0YtGLVgsFhgwcLCsObAAYJiuEpUghbMfvCAocfFBa/Y7AcPcBbbBC3QlZHBqBPQxXRlZHDW0VSJAwsW3G0HAAGRQafW3JvAAAAAAElFTkSuQmCC",
  #  0.19  Claudia Gold
  "Claudia Gold" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA0UlEQVRIie2VIQ6DMBSG/y6onoOkbpoDILFo7kAd0+DKHdCzlRwAjWuyc1SRFLGMZUnXQjc2w6+avNf/e3+fKKm63mBHRVuamyJdzlXXfxfQFCmmIX5eTNJVkFOIOQBMQ/ySKBhgM98CWZXgEzkBrukf8qX4b4IDcAAOwA8ARrerTFx93v8gSm7B5l4AoSWEEGCMWetKKRBawugWdT7icj1vAwAAYwxZlllrUkoIIRaITbsv+W2COh/RFPdnkFJae5RS4JyHL9noFoSWzgl9S54BQU1M5YjxtWcAAAAASUVORK5CYII=",
  #  0.20  Marc 1/1 7
  "Marc 7" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA30lEQVRIiWOsWrjnPwMNAQspitviXeDsqoV7qGtBW7wLQ6G9HAqfGEuYyDGcgYGBodBeDsVHZFuAzXBSLCHKB5QAvBbgcz0MEPIF3kieqCDFwPDwD14LGBgYGFJEBcmz4PLX73gN1uXmJGg5hgXi9XEINgEDLn/9TtASDAteNi6Cs9viXRiC9MRw6+ZjZXggyMIw5+B7hiocSihKRfKCHATVEMzJxBiCDwxsPhi1YNQC6ljw7PkjhmfPHxEUI9sCKWEOhpW38IvhK7IJ18lsYgyF9kSI4QBUiYP+g7iDCwBbGT0eUbgGqgAAAABJRU5ErkJggg==",
},

###########
#  1) Mouth
"Mouth" => {
  #  1.0  Bubble Gum
  "Bubble Gum" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAmUlEQVRIie2UUQqEMAxEZ2R/9VZ6ifV49RL1VvUAsx9rpdouKwbBjw7kI6HMIwkNJeFONbe6V0AFVEAFPATwKhVJxhNL67XNACQVnI+pSJpAuxEdzAEAax5B1wGpefvuixATINUyzVnt2JkJUFI3DmYAf5l044Dg/KUl7DoIzmcQizkAQNIWKwT4LlQAFJzf5p++PRvmj/RPH0ZoaDPCJBCcAAAAAElFTkSuQmCC",
  #  1.1  Medical Mask
  "Medical Mask" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAeklEQVRIie2VQQ7AIAgEl6Z/4Cn+/+hTeMX2oj0ZobVeGvZkgOwgGhWS2Kljq3sCEpCAnwBOr6DWGvFhKUVGiS92QABD8yhg9txOzaMAaUY0M/Z1xDwKuKWqT8rjADMLxd4COOq8xfqolgCzOYuTX7qm7gEDgOSn7+kCh2sfJynhAPAAAAAASUVORK5CYII=",
  #  1.2  Hookah
  "Hookah" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAABD0lEQVRIibWWQUrEQBBFX3WaJJCs3I33yM4LeIjsvYIn8AgeIIfwAFkMTM4gCIqzEVcBh8BQbiZDp2F0RqsLGpoqeJ/61Z20qCopwyWlxwKbda+bdZ9OABBTeijw+vKcZBhhBwKYi4QCSkqLUsBjAUhp0Xb7nt6i1eravAMPUJdZCFZAxt3eRECqwmnb5ItkN0xYiThADsAjvG1ys1lIVTi9v71aJB+ePsGoAw/w9jH+G3QqklvkAdoml26YdN5bwQH8uNtTl9ki2Q0TVscUVUVVqQqnh3XMhbW7m1Krwmlc+22d9ctsm/zPs/E/Fesymy+hxJfx3DjZwQyPT9ilIfOzJfgeCaCxLY/918VwgG/JupUkSQJv+AAAAABJRU5ErkJggg==",
  #  1.3  Pipe
  "Pipe" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAl0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCwbGAl9aWuCLRlPdApoARnqXplSPg2HiA0ZGRkLq/jOQ6VuYD/6j45YAEYaWABEGGBsqTjJggTGghjAwMDAw1Gx4A6P/twSIwPgEvYkNwOPgyZsvKDSy4S0BImQZzsCAGgf/M2w4GGREeOCSyIbXbHjDQE4coEcyugkoLifHAgBDN0Tty2CRVAAAAABJRU5ErkJggg==",
  #  1.4  Cigar
  "Cigar" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAiElEQVRIiWP8//9/DAMmWIJFjCzAREvDcVlAVUAXC9CDBFucUGQBTQHMApr5gq6RTNXkic0CqkYuNgtoAnBZMFpU4LWAZjmZ5smUJhaxoAswMjL+x6bw////jBRbwMjIuPhBjApDx8dvcLEp1VwMOa3fMDQSCxj//0d1MLV9gGEBtcHwqDJpCgCMfyAuP9ohagAAAABJRU5ErkJggg==",
  #  1.5  Vape
  "Vape" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAATUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVgqFjAgsxhZGTEWfv8//+fkWILGBgYGBgc/jBESMSQYxZWwIhcZdLCB4yjdfKAWwAAwq0TMVkCngYAAAAASUVORK5CYII=",
  #  1.6  Cigarette
  "Cigarette" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAV0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC3BaEENrC6gKRi0YeAsYaV0fsGDYyMiI1cb///8zUmwBIyPj/wcxKgxPMhaQYxZWgBFE1PYBzeNg6CdTmlsAAKQNGM923QQiAAAAAElFTkSuQmCC",
},

###########
#  2) Eyes
"Eyes" => {
  #  2.0  Tears
  "Tears" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAN0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtoJIFrYd+/2899BtDjGoWUAoYR4vrUQtGLaC9BQBFKQ7tFy2M2wAAAABJRU5ErkJggg==",
  #  2.1  Monocle
  "Monocle" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAn0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWMjRFBIYDMv+jGvWr8WrlmQfQA1nhOL/IYHB1LWAVEBOEDEyMDD8R2LjBeT6gJGBgYFxZcUlgkUxIznFNXK4Qy1hZGBg+M9sfhvDR2RZAAN/T6rCmP8ZGBgYmc1vY6gh2YKHDx/ilJOXl8cQG/o5eehbQFZZBAXIqQNnhqMomRIDAEwXKQgIQnU3AAAAAElFTkSuQmCC",
  #  2.2  Lasers
  "Lasers" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAfklEQVRIie2UwQmAMAxFX8UVvHYJB3KSbujVBbw6g3wvuUhpelAPQj6Ukh/4j1CaJIkvNXyaHoAABACA0e2mBJCBCTiA3Tp3z9kGvQkysACr3bnhtSWpfWAW6Nw2CWR17TkZPUAWFAsqVteek5HcbfrCG/iAF/T/fxCAADzXBZwtjsftAvnSAAAAAElFTkSuQmCC",
  #  2.3  Pink Shades
  "Pink Shades" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAg0lEQVRIie2UOQqAQAwAJypro4X4B/H/rxG/oY2yGAsVsfBYxELINIEEMiGQiKryJdGn3U1gAhMAkFzUQk9cQgW00pCR4XCkpOTkdHQMDIyM9PRUWp82h4AV+diDRksM4LGg8CWArPExcvNN96JMsk2feHfIo+dz3gle8/87MIEJ3jMDF14kYp/uzdQAAAAASUVORK5CYII=",
  #  2.4  Aviators
  "Aviators" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAa0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWPBJ/j2pSnQ2Zza/zYhNnKAPWCzunGWxuHMW2RBkMQYGBkYoxgpoHkSM+Aq7vydVGRgYGGAKkF2JIsZsfps8C6gBhn4yHbVg1IIhYAEAcRca0w92qy4AAAAASUVORK5CYII=",
  #  2.5  Polarized White
  "Polarized White" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAiUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWHBJfPz4kaQszs/Pz0iSBQwMDAwZCn0EDZ7xoIiBgYEBq+EELdDktETh51+3ZJioeZygpciAEVdh9/Hjx/8CATxw/ocNXxgYIC7FKs7Pz0+yBQwMDAzIksjBgCFOsgXUAkM/H4xaMGoB5QAAKHMmk/RCeBwAAAAASUVORK5CYII=",
  #  2.6  VR Headset
  "VR Headset" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAh0lEQVRIie2TwQ0DMQgEx1F6cYHUQTc0QzWbx+V+BkXK3eMkr8SLFWOzYkjiTr1unb4BG/AMwLtqjDEAfrnCw1gcbAkA5O7MOUtDZmJmOiHrKdKyAEWEOH6xrIiQu6ubc1UG5Sq7FZGZRETbNzNoVjSqcL4ht687rVCHXAKu0vMPbQM24H99AEP4V2NNTMrgAAAAAElFTkSuQmCC",
  #  2.7  Gold Glasses
  "Gold Glasses" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAaElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWPBJ/j2pSnQ2Zza/zYhNnKAPTkrcbjwpcbsRymXEIYbVcKIsoBQw4ivs/p5UZWBgYIApQHYlhhiz+W3SLaAGGPrJdNSCUQuGgAUA1xcbHgZrW+sAAAAASUVORK5CYII=",
  #  2.8  3D Glasses
  "3D Glasses" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAa0lEQVRIie2UMQrAIAxFX0pHIVfyMD1WD+OVAu52qlMrCjoIyfRD4D/4JJFSCivrWOruAAc4AICzNTSz7jNXVRkGAIQYq84pEe9Q+3TlV36aw5yIfs0BpPXsOiMSAFUdB8yo/dfUAQ7YAPAAHTQXKw+/JEIAAAAASUVORK5CYII=",
  #  2.9  Clown Eyes Blue
  "Clown Eyes Blue" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAaklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWIhRpBm58T8DAwMjmvD/68v90cVIt0A3cOp/LIqILl8IWvDnzQUGBkzXMzDI+BB0PVEWXD88mxFLEDEyQHxB0BLG0dJ01IJRC4aBBQAvNhbSG3MYogAAAABJRU5ErkJggg==",
  #  2.10  Eye Mask
  "Eye Mask" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAWUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWPBJMjIyEp3N////z4hNnBgfMEIxITGsgKggevHixX80PoYYTtfhK+yoEUR4LaAGGPrJdNSCUQuGgAUA9JcbUTqITD4AAAAASUVORK5CYII=",
  #  2.11  Big Shades
  "Big Shades" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAf0lEQVRIiWP8//8/Ay0BE01NH7Vg1IKhYQELLglGRkZsOZCRgYEBqziuDIvTAgYGBoZMHlc4e/qX3Qwww3GIM5JsgTKjGAq/hzeaseTz0v/o4rgMJ2iBoggrgvMZyv+MKY4P4Aw7RkZGBgbU8EZ2JYY4TnNGS9NRC0YtGAYWAAABYSMopPi1JwAAAABJRU5ErkJggg==",
  #  2.12  Nerd Glasses
  "Nerd Glasses" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAYklEQVRIie2UQQrAIAwEZ4sP95ke/Es8ldJaYlvqQUhu7oKTDRqZGTNrm3p7AAIQAACSZ0q6fnMBneZtg1EC5VrItexnA7jTvgI64EPtML14kuDc4esRueYftf4zDUAAFgA0GiUd+ECgGV4AAAAASUVORK5CYII=",
  #  2.13  Small Shades
  "Small Shades" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAASElEQVRIie3UMQoAIAwDwET8/5fjJg5FRIiDpFNpIQcdSklwVrOmBwgQ4A3Qd0uSR39EEq8AAASgpZ+Zxaws+4mYbxogwAfAAOxwDC7ms2i/AAAAAElFTkSuQmCC",
  #  2.14  Glasses
  "Glasses" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAZUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWPBJRoWHEZ3Nl61cxYhNnKAPps+a7Th91mxHZEOQxRgYGBihGCugeRAxEirskIIJ2ZUoYstWriLfAkrB0E+moxaMWjAELAAAXJQcV/O/i9IAAAAASUVORK5CYII=",
  #  2.15  Clown Eyes Green
  "Clown Eyes Green" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAaUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWIhRpLnR9T8DAwMjmvD/6/670cVIt0B3quN/LIqILl8IWvDnwhcGBkzXMzD4CBB0PQMDAwMjMYUdJUFElAWUgKGfTEctGLVgCFgAAFOCGU7EsdfBAAAAAElFTkSuQmCC",
  #  2.16  Eye Patch
  "Eye Patch" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAASElEQVRIie3UQQoAIAhE0T/R/a887SMJgiBiXLlQ30JUtrkZ7er0AAECANB3BZK2p25bxwAwN89gORwe3YGKfF2cbxogwAfAAHMNCzAZgR3UAAAAAElFTkSuQmCC",
  #  2.17  Polarized
  "Polarized" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAiElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRCxgYGBgYWHBJMDIykpTF////z0iSBQwMDAwRAnUEDV7xoYmBgYEBq+EELdDktETh1z/3ZGiU3I6q6AN+BzDiKuwYGRn/Mzj8QQgcYGFggLgUqzhOc/BYwMDAwIAsiRwMGOIkW0AtMPTzwagFoxZQDgC5+SWD/mXSOQAAAABJRU5ErkJggg==",
  #  2.18  Classic Shades
  "Classic Shades" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAaUlEQVRIie2UMQ7AIAhF32/q7HlMPIo38P4znWxaE7WLSwMT+ZD/YACZGTvj2OruAAc4AIBzVpT06czNTKPacoOSIiXFlqvXgKH5J0DNgZrDnffaKjR7dpIAWsNz0pc29fBv6gAH/ABwAasyGLn8a4ScAAAAAElFTkSuQmCC",
  #  2.19  Deal With It
  "Deal With It" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAVUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC+hjAQs2QUZGRpLKj////zPikiPogxOHjsHtJUYcm+0YGCZ14tCx/1AaRQu6ODYzYJhxtDQdtWDUgmFgAQBeTUHhSsX9OAAAAABJRU5ErkJggg==",
  #  2.20  Regular Shades
  "Regular Shades" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAR0lEQVRIie2UMQoAMAgDm+L/v5zuYrCLHUqcAoE7XAKSa/L2KN0CCyx4IwhVALjeEJJQXfcBUq5AEt4JMrzLNcRraoEFHwgOR/AKM/pGq8sAAAAASUVORK5CYII=",
  #  2.21  Horned Rim Glasses
  "Horned Rim Glasses" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAYElEQVRIie2U0QmAQAxDE3EQ93A4cbju0U3i130oV/DA+5Hkq6SlrxRaSsJMLVO7G2CAAQCAtUqQHDpxSRwCNEXqbPG+8ai8SuWKJPE5VaQYefd6da8AX4n+pgYY8APABdqOI28g82DKAAAAAElFTkSuQmCC",
},

###########
#  3) Lips
"Lips" => {
  #  3.0  Hot Lipstick
  "Hot Lipstick" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1AIoYCFW4VElQXjVZ33vPSOx+hhHq8zhbwEACB4KKz/WIz0AAAAASUVORK5CYII=",
  #  3.1  Purple Lipstick
  "Purple Lipstick" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1AIoYCFW4TnGM/Cqz+i/CSOx+hhHq8zhbwEAD8IKK4mZ4Q8AAAAASUVORK5CYII=",
  #  3.2  Black Lipstick
  "Black Lipstick" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAN0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1AIoYCFWISMjI7zq+///PyPR+karzOFvAQD8kworGHKe9AAAAABJRU5ErkJggg==",
  #  3.3  Buck Teeth
  "Buck Teeth" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAM0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1AIyLPiPRlPdAkY0muoWkAVGLSAIADc0BS1B08qdAAAAAElFTkSuQmCC",
},

###########
#  4) Facial Hair
"Facial Hair" => {
  #  4.0  Full Mustache
  "Full Mustache" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAVklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLWASoCFkIKlubr4KgzG6MmX8erH6wMChjMwMDD8X5qrS54FWAxnRMJEW4LVAiJcjg5wqmccrZMH3AIACmcWY9QaO50AAAAASUVORK5CYII=",
  #  4.1  Full Mustache Dark
  "Full Mustache Dark" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAVklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLWASoCFkAIfY1F8FQbjlrOv8erH6wMChjMwMDD89zEWJc8CLIYzImGiLcFqAREuRwc41TOO1skDbgEAqacTDLqVMr8AAAAASUVORK5CYII=",
  #  4.2  Front Beard Dark
  "Front Beard Dark" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAXUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVgqFjAQoyiTHcFjFpp+s4HjFSzAAqQDSS6GiTFArLqVmLjAD04iAoeUiwgGzAS26pgZGSEK/z//z/RPiDaAnIBAEs6Eyzz2K4bAAAAAElFTkSuQmCC",
  #  4.3  Luxurious Beard
  "Luxurious Beard" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAcklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGCkWsOCTZGRkJMaM/////8epkBgf4KswCFYmeH1AikGUWsCQYcABZ8+48INoCxjxVZmMjIxEuZySOGCEYkJqcAJigug/DkOI8h0xFjDiMYxgOsYbB9QAAO5SGi9bE7wwAAAAAElFTkSuQmCC",
  #  4.4  Soul Patch
  "Soul Patch" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJBaQEjI6MDqRYwjtbJA24BAP5RBmyWuLcEAAAAAElFTkSuQmCC",
  #  4.5  Big Beard
  "Big Beard" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAkElEQVRIie2W0Q2EIBBEZy6WgwUdRWAtUgQWdPSz/ohRs6AmZ/zZ+dqEzTyGJQGKCJ7U51F3AxjAAAYwwJ/UtRanoQeA1oPBUnzHn9pQTUBSTswLXHzMIKk2NBNs5WNeHVJwO3AKTnzMwCbRbcDR9KreHfIV1Y6miLVfxTI0ScHVTNfWUmheZwBAv0nqjjWvGb9GKe/UTYWoAAAAAElFTkSuQmCC",
  #  4.6  Big Beard White
  "Big Beard White" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAhUlEQVRIie2WwQrDMAxDpbF79P9fqXyBd1lKV5y0g5VdrJMhRi+KAwkjAnfqcat7AQpQgAIU4Ed6rhZ77wCwejA4itZa2jBNQDJOzAc8JIFk2rBMsJekzcH2B9h2SAJ2ib4GHE2v6r9DvqLZ0Qxx9qt4Dy1sz0y31lFkXmcAIL9J6Y4zrxe0Mihft+NLRgAAAABJRU5ErkJggg==",
  #  4.7  Front Beard
  "Front Beard" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAXUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVgqFjAQoyi5fm6GLVS5MTLjFSzAAqQDSS6GiTFArLqVmLjAD04iAoeUiwgGzAS26pgZGSEK/z//z/RPiDaAnIBAFQ2EyxkXNwZAAAAAElFTkSuQmCC",
  #  4.8  Chinstrap
  "Chinstrap" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAcElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGCkWsBBSsDxfl5CS/5ETLzPikiTGB/gqDIKVyaCOA5jrcQYPpRYQBQhGMgPEhbjCGq/rGRiI9wG6QYzEGM7AwMDASGyrgpGREa7w////RBlOkgXkAgB1ihUr14oEegAAAABJRU5ErkJggg==",
  #  4.9  Goat
  "Goat" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAWklEQVRIie2WsQ2AQAwDz4hxYCCWeGZhCRiIgUyBRO0mDUqkdLmcUsWyTWVNpdtb0IIWtKAFLfiNYE4Hr339nvd23Eq58guwHTXgcyx+kYyxjdLYIgnAkDMAD1SDUSdKMMMGAAAAAElFTkSuQmCC",
  #  4.10  Mutton Chop
  "Mutton Chop" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAATUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGCkWsBBSsDRXl5CS/9GTLzPikiTGB/gqDIKVCSVBRFRNRY04wBk8DAwMDIyjVebwtwAAgUcNKTlRF/EAAAAASUVORK5CYII=",
  #  4.11  Goat Dark
  "Goat Dark" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAT0lEQVRIie3WMQrAQAhE0T8hV/D+B9Q7mC6wnVsshDA2NuoDG1V3czKuo9MNGDBgwICB3wD3tDAi3uOdmZr2fWdFVbXkaWj6tkgC6J0egAdUghOzQwOLFwAAAABJRU5ErkJggg==",
  #  4.12  Handlebar
  "Handlebar" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAASklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVgqFjAQoyig52u/588eQHny8hIMNiX72akmgVQwxmR+ERXgzQPIsbROnnALQAAPvMTjUrqRjcAAAAASUVORK5CYII=",
  #  4.13  Normal Beard
  "Normal Beard" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAYklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGCkWsBBSsDRXl5CS/9GTLzPikiTGB/gqDIKVCUEfEGsQpRYwMDAwIAcD0RaSYgEuQ3GGPwMDcXGAzwC8hjMwMDAwjlb6hAAAJ5MPMG+kMRsAAAAASUVORK5CYII=",
  #  4.14  Mustache
  "Mustache" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVgqFjAQowiV0tNjFpp9/HrjMToZRyt0UYtoBgAAKfeCiv9Ht8EAAAAAElFTkSuQmCC",
  #  4.15  Shadow Beard
  "Shadow Beard" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAATUlEQVRIie2VsQ0AIQzEfIjdmJnp8s23hEgI0ZyltHZxRRQR3KRdtTvggAMOOPAjaXfjKABkglQO0AuBkmjF+w0KzNNAJkjlAPLT3/EB/+MJjYqtYVUAAAAASUVORK5CYII=",
  #  4.16  Normal Beard Black
  "Normal Beard Black" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAZUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLWASMDIyIi3vCdoASMj439GRkayDGdgYGBgIaQACnBaQi0LGFoiZODsmhVPiLaAkVCVSUQw4DWDmEjGFzYEw42gDygFgz8fEAIAY1EUNuv2V04AAAAASUVORK5CYII=",
},

###########
#  5) Head
"Head" => {
  #  5.0  Uncle Sam
  "Uncle Sam" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAT0lEQVRIie3TMQrAIBBE0T/2uf9xx8JKMCBGCcj8Zjsf7KJsc7Jy9PUA3wHJgKemtABs6GfARs/cfEvDj9Z2u5bdHWMMbOz2IwcIECAAABXm0iNiWqx62gAAAABJRU5ErkJggg==",
  #  5.1  Bunny Ears
  "Bunny Ears" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAzElEQVRIie2UsQ3DIBBF/0XJEJRuLNNkAcp0NBnCgyAvRec5kLKAxyCNbZ0PiAvLkRJxkgt8//7jOATFGHFmXE51/wvAtZQYnePDoccw7GmyumwHvPA1TQAQR+cSzZzjkegSgDRvjCkWP/seGUgZkGkZ966DtnaFSF1jjIRsPEozIABolYrB+02Cmwfvcfu4//SIaDFf1tpa0tYSy63f/B+tUhB1RcAay20I3kN2wTuQG5IgOvpUzIOP3Jhf1cOAvfj9p6ICKqACvgB4A3CRUQay+cBSAAAAAElFTkSuQmCC",
  #  5.2  Marc Three
  "Marc Three" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA5UlEQVRIid1USRLDMAiTOn0Y+Tk/Uy8hdWrjpWkuZcaHOCCBAFMS7rTHrej/SUBS+4nvJcAyFgCeLR8AAhCOQwaS6aS0JCqdZ9NP/VoEa5oM4kdNVuzJQi9OclUEO2CgcRG8IskqmF7vRoOJQqbhHkT2C0/KybE1ppGFFoCFd9b9Hly0kggAwCxDkpI03d2yF2VcWsEKOACYGcwsyI77n0nk7gcRJsa0erS+tSYBSUW5txBcMXeHmU0v2nWZJFUnfpmZUCxc74RvSBv32SYDAN09ArRt2zEp6OzPVAUfwVFFt6Ls3wvWJqjpFe2W9AAAAABJRU5ErkJggg==",
  #  5.3  Viking
  "Viking" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAsklEQVRIiWP8//8/Ay0BEy6Jbw/n/f/2cB7RBuFSj9WCbw/n/WdgYGAk2nQIYGRgYMAIDpw+oBbAZwGpkYNVPQshTWF67CgCX2WdGLgf70MRW7B5Ok4DcPmAkYGBgSHBNxNDQlFRAUMMSR1GvOELIqyRfP/+A5LUY7WASz4Jp63YfIAPMOLLaDk5mf/v33/AoKiowECIfnVoHuOqSz9Js4AaYEDzwagFoxaMWjBqAb0sAAArUD399x7WhQAAAABJRU5ErkJggg==",
  #  5.4  Laurels
  "Laurels" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAeklEQVRIie3TMQ6AIAwF0Na4MfcG3oFD6HV7CDkDN5CVzeQ7mTAggQS3/rFN/kuHMgD6M8uv7QZMAUQ9RH33fAgQ9bhjJiJCz3wIeEvWzVE6Ape7az953RzdMZOobyJVoFX+Jh2hC/m6gMvy2jMC6ELYPtkAAwwwYEIeZmBDAAE19zsAAAAASUVORK5CYII=",
  #  5.5  Shemagh
  "Shemagh" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAlUlEQVRIie2UsQ6AIAxEW+Oki/z/R9JF1nOSSKBIjR1MfAkLkLvQ9mAA5Mnkqv4bjDDfXUgiI1PAy7Y1D7ovGBQnIkISsRkYxLsmrOWAmZ8EpNJTe7DHaFZfQ6g3ATSXlT1GtPTUEmlN63AKFROllkgbO40kwheTjEfQiml6zeBR0CxoufH6i3KZvv+behrA24B+gyEOfNhZ2d0j4NwAAAAASUVORK5CYII=",
  #  5.6  Welding Goggles
  "Welding Goggles" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAeUlEQVRIiWP8//8/Ay0BE01NH7VgUFjAgk9SVprxv7kRhH3yHEIcTYzx8VPcKRGvBeZGDAy6/bcgnEI1hpPnsIr9Z2BgYMRlBs2DiBFfRsMSRIwMDAwYwfb46X+cPiBoAQMe70PBf7ItoAYY+vlg1IJRC0YtGA4WAAB4ISt/p87sggAAAABJRU5ErkJggg==",
  #  5.7  Beanie
  "Beanie" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAZklEQVRIiWP8//8/Ay0BE01NH7VgZFjAgk/yOisrPA3zPRfGkJcpXQNn/59vw4jNDKJ8gM1wBgYGhifdIQT14vUBAwMDIwMDA0PEjZc4c+OT7hBGZJ9gGDCak0ctGLVg1IJRC6gAAClNFRLceqe9AAAAAElFTkSuQmCC",
  #  5.8  Top Hat
  "Top Hat" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAWElEQVRIie2TOwrAMAxDrVB8//NmUYZOAZMPTigFvdXgh4QNknaTcnW7BCs8oyGAnQtAdDDfJqB7WhDGMnvroTtQa6qmULDZfQdJTAUn+f8fSCCBBBIs0ADz4R0wrHqGfQAAAABJRU5ErkJggg==",
  #  5.9  Marcdonalds
  "Marcdonalds" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAiUlEQVRIiWP8//8/Ay0BE01NHxYWsBBS4OziiTeSnjy8y8DAwMB48/YtrPJ4fYBs+J6aHSg0DMjIKzMwMDDgdARRQbSnZgeDS4sHCk0swBtEUO8zMN5nZHjy8C4KTSxgRM8HhMIc2XJo8DA8eXiX4ebtW1htxbCA2mDo54NRC0YtGLVg1ILBYAEAPq4zrju14kEAAAAASUVORK5CYII=",
  #  5.10  Cap
  "Cap" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAX0lEQVRIiWP8//8/Ay0BE01NHxYWsBBS0CS1g5hIYqx75oFVAq8PYIYbeqgSYQd2QDCIDD1UGc7vuE1IGU5fYgQRepAQYThegOIDIsObJMA4mtFGLRi1YNSCUQuGggUAw+kYJTbizj0AAAAASUVORK5CYII=",
  #  5.11  Roaring Headband
  "Roaring Headband" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAdElEQVRIie2UUQqAMAxD88RTeP+ruWvUD0VEVqzQIbLlax8ladoumJlaYmrKPgT6EJifCgpE7pjFOfcsB4bTyPcjkkSgxh1jlgO3CTKyqLDz1xadIiBJgGpcaQIe/v+Th0AHApEsOgHYejy9eL4j7OBC/gob2iAfEPDPku8AAAAASUVORK5CYII=",
  #  5.12  Blonde Bob
  "Blonde Bob" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAiklEQVRIie2V3QqAIAyFz8KbHrcn8XG9XBcjyPlbw5DwgJC67XMbKTEzRmobGn0BpgC46m7wDIAAAPvRtsvYlDMQp3rgWIzgOwFXcPnuBchhlP0kTe4t0z3zRwCD7ACpOY0DNGQHSH+KV3IKyDTKoo9L9Ob0qU801xmQGuJQ+pvj4NpPFteT+X/ACQgmK1hoUkqZAAAAAElFTkSuQmCC",
  #  5.13  Purple Hoodie
  "Purple Hoodie" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA6klEQVRIie1VQRLCMAhkHb9kn2KfYp8QnxKfEh+1XopiCxgde3BGZrgUsmRhS0BStrTdpuj/Aj22f5UAoEcFiMQSBhS8lvYSfZyGECtsUS+4iMicRwBrHK/qEny+YQZu854w0xkcTwfMM1hf7QGaMu1RUQiu8XEawpxVAdse21OSrlvzZhEysH3PlGYKuSzSFtXSUvAuW9BlLY0ioh62xvNa2v28fvvaqgBAT86/v+w2L+Bp2g66e8D2nKrPHXItDeM0pAvsYwbKQsHfYWJvb/NXy46kAFAmeoCX89X+3ek7kjLwmKhnjKLYDc84ShHOtvdtAAAAAElFTkSuQmCC",
  #  5.14  Do Rag
  "Do Rag" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAbklEQVRIiWP8//8/Ay0BE01NZ2BgYCFFcVp8PLJ3GWctXEhQD9E+QDacU0CAgYGB4X9afDx1LEBzOcP3Dx/gllDFAmzg+4cPRKkjaAG660mVp3kqGjTJlBGPHN4gYhzyOXnUglELRi0YtWAwWAAAqfQc2wzZXZoAAAAASUVORK5CYII=",
  #  5.15  Fedora
  "Fedora" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAaElEQVRIiWP8//8/Ay0BE01NH7WAGMBCSIGjgQwxqYBx/4UnWCXw+oBIwxkYGBj+OxrIYLcZXzJlZGQkJQ1jNQurIAkux2oRcnBhBBGFhjMwMDCg6McbRNQAQz8fjFowasGoBaMWEAEAlpEdxoeu0nsAAAAASUVORK5CYII=",
  #  5.16  Cowboy Hat
  "Cowboy Hat" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAc0lEQVRIiWP8//8/Ay0BE01NH7WAGMBCSEGVjxAxqYCxbcs7rBJ4fUCk4QwMDAz/q3yEsEqg+ABqINw11598IdJ8BgZNGR4Uc9q2vGNkYGBgYETOByS4mCCAWYAeRIxUMh9uDuNoTh61YNSCUQtGLaACAACJyh/ZISpkigAAAABJRU5ErkJggg==",
  #  5.17  Police Cap
  "Police Cap" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAl0lEQVRIie2TQQrCMBRE34hnsWs9hp7AE3qC9hh1HS8zbiqK/qQpWEHIbALJZx5/hsg2a2qzqvsvANvaQUlRlpqLuDjwarrbHz/eb9cBQIBzXlmAJEem6TLQnWOYbb3fL+4gMi+p1IEA0thbErbJnd3hpGhbmI/okW+oqQOmOdLYLwPwLDBUlHk14Fv6/5/cAA3QAA1QoTttxEaJn/QjWwAAAABJRU5ErkJggg==",
  #  5.18  Cap Forward
  "Cap Forward" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAg0lEQVRIie2TwQnFMAxDpU/HyBoZJJN6kKyRPfQP7S+Fxm4P7eGDBT4l6EVGoSS8qc+r7gm4o+XqAkm11qZnYwz03gGAXlnCBJE5AJRSUGsFALeKLplk2N8j2Mxcn+mKSGp7mSszQ5Rul6TTYI2sQ/xwZh6/caM9pf//BwlIQAIScENfbn9SH/k0ra8AAAAASUVORK5CYII=",
  #  5.19  Knitted Cap
  "Knitted Cap" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAY0lEQVRIiWP8//8/Ay0BE01NZ2BgYCFF8Wl/IWTvMppufEdQD9E+QDOcgYGB4f9pfyGC+ojywRQLLlwR9d+UgYERn16ifWAuzoGVJgQYh3wqGrVg1IJRC0YtGLVg1AIGBgYGACrgEo9E34IRAAAAAElFTkSuQmCC",
  #  5.20  Tassle Hat
  "Tassle Hat" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAzUlEQVRIie2U0Q2DMAxE76rOxRhliGYEPsMGsBCLHR8BREmcIJVIVOpJyEhO/BLbMSWhph5Vo/8BlwHY9uJIJW3bfwdg2wtNB0weSQvkIZKyHwYIL6+CNffTegckhQH7k6a1+l3Ydoz3LKVoSQcz/uxLLQMAbqCUJs8c5AwAaDrobaQS9uWAk21qBT/4kqR7PLRTGkLL1wM4iIyz9EMpuhVgGxNB4mj3OkeGyob1UZWtG3CZLeE/J/dh47XJCbpzr6czp20hnjlNr1L1Is/gnK4J+jZE5QAAAABJRU5ErkJggg==",
  #  5.21  Hoodie
  "Hoodie" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA3klEQVRIie2V4Q6DMAiEYdmDnU8ub3b7MXFoC3VmLlkyk/6x+JXjKCpJufK5XUr/H3DkuY8CVPVIF2jWLOmGwwEM6WaWstISHYWLiCxxVNWW0zt1D18yrOAxbsMceaBmRgBtai9oqXRossMzFeHwrplNiXblUQenXaK6ehASWbmpyRFcdRpJmedZRKRbxssv2prhkiUBUJ5yud8frfi9v/uYguzG//6w+7rJIlujTxkMQFKTAaiZlQPstAJX4fB3lMTsY3wzi0j69dcwyDhNU5xH5X+kVNBT4qtSlO09ADTmMKiGdudPAAAAAElFTkSuQmCC",
  #  5.22  Fast Food
  "Fast Food" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAc0lEQVRIiWP8//8/Ay0BE01NH7VgZFjAgi4wSVEamUtUGr789TvD7FfvGImyAF0jPqDLzUnQcmwWwF1NyIDLX78TVINhQf6DZ8hedcXvPgaGFAaG3fjk8UZyiqggXs2E5BkYGBgYR8uiUQtGLRi1YBBYAAAJ2BqVs7kA6AAAAABJRU5ErkJggg==",
  #  5.23  Tiarra
  "Tiarra" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAXUlEQVRIie3SMRKAIAxE0b+Ow83oOK6dN7NZK6WEFFCFOtlHILLNynMsTd8BnNOVtwwI6G9arVFbZIIvXICoc38XAUwr0CcY3j4KiOuBVqaC/6Zc0wQSSCCBBHYAL6tQEMSYG9L6AAAAAElFTkSuQmCC",
  #  5.24  Stringy Hair
  "Stringy Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAP0lEQVRIie3RIQ4AMAxCUf7uf2dm69Y0qRoYVHmi2NZmzur6BAAM7ACAJSGpjbSBOl76ffffkwMECBAgQIBJLqguDDWlOAr+AAAAAElFTkSuQmCC",
  #  5.25  Purple Hair
  "Purple Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAg0lEQVRIiWP8//8/Ay0BE01NHxYWsFBqQBHvCVgkMvZ9tsCQp6YP/hfxnvhfxHuC6hYw4mBTzQJk8J8B4hPqWYAl3FF8QYtU9B+KGRgYqJCKsAD6+oBaFjAy4EhNtMrJ1PUBNCXBczQDjX2AUv5TOxXRJSfT1AJGBgbU3M04WmUOfwsAaeofLlw0sqwAAAAASUVORK5CYII=",
  #  5.26  Skull Cap
  "Skull Cap" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAgElEQVRIie2TSwrAIAxEk9KrRO9/HPUw6UqxVk2EWihkVgHDvPxEZoadOra6G0CjU0rw5DRXgCHF/sPsimrz2sCTU0NUIwopFlNPDkbVdqkrHWTzQQdtUQiwsOS6A4UwB9KSS2I7lgHoMQ7xigTDXkE3yHQHb+j/P9kABjDAB4ALX24tfte1vc8AAAAASUVORK5CYII=",
  #  5.27  Headband
  "Headband" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAO0lEQVRIiWP8//8/Ay0BE01NH7VgZFjAQoQaYtIxI9kWSOZeJWj688nauG0ezWijFoxaMGrBqAVDwQIA8wYKLZUQftwAAAAASUVORK5CYII=",
  #  5.28  Clown Hair
  "Clown Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAoUlEQVRIie2UPQ6AIAyFX42X4R7OcFdnOAfcBhcxVSjgQEwMHSm8r79QjBEjbRmq/gvA2rqg9i01iby23b5k1Qy4gHAlnUe1b+8ATLzXipAi4CFOAFAqwXnGs8sgw5tMfNGEsogNrL3z2hLwwR5k09KKXrBLp5TB5fTakjR+lcBuQd4ALFoCgE5xCZQDOCQYh2Bcl+pzXHlZaX7XEzAB4wEHUF069hi7riQAAAAASUVORK5CYII=",
  #  5.29  Vampire Hair
  "Vampire Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAfklEQVRIie2U2wrAIAxDk/3/P3cvOmSoiRPZYObFFm2PrRdGBFbqcBeSDJJNvxnnVEAyABBAuTj73RyygiJ5dVrFOy1ixc6jLN8+g6eXwQFcmROEN7tLHm3RsKxbNCP7DFpSb2EaIDfw+RZtwPuA9BmuAyhNAdTugf0OfgE4AVTMJizegxdVAAAAAElFTkSuQmCC",
  #  5.30  Chad
  "Chad" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAoElEQVRIie2UQRKDIBAEZ1K54G/xIfpbPU4u0aiBZUvgZh+BopllgZKQgqQAMDfv5ZXbXMsEACLZXrDRQmIKDhJgnfsIdkLsJ9AyuRKkSukRVN2yv0QW66xvW98QhOiq/9Zx1/G343TFJRa5BOQwnkdudpGV4He51uaFhMkEtf/PkWwCtyREM0WbNjXeSisBOIyQ9Ceq/u9LNEvwCB5BPz4niDK9/dcreAAAAABJRU5ErkJggg==",
  #  5.31  Bandana
  "Bandana" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAv0lEQVRIiWP8//8/Ay0BE01NH7WAGMBCSIG4xVJiUgHjyxPR2CXwpSJxi6X/WXhUCJr+58sdnJYMeBAx/vlyB8UXUNciDOBRYfj39QYDE7fGf2mXkwx/vtxhYOFRYXi6x5yRGAsYWHhUGP98ufMfmY9N3b+vN/7/gVrIwMAAV4M3iF6eiIa5iBGGYb6AYWTf/vt6A9OBhHzw8kQ0g7jFUgwxVGDOIKpbC3M5SqrBm4qoAYZ+Th61YNSCUQvoYAEAHYZGBvVdgXMAAAAASUVORK5CYII=",
  #  5.32  Crazy Hair
  "Crazy Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAtklEQVRIie1UQQ7DIAxzpn2Dc/7/nJx5SHYhqNAEUDukTaolxCHExkaBVBU78drK/g2BzKyZOazTKKLMrAAIgAKgJOLVK1dfB9YcmIh7wVlzKNDdbgXqxXWKyCEmAPDsOz3mSJMIAb6Dqe0BtKyKKCI6CjmPOxJpek8CHVnoxkTKHp5zHSSRYeZWC5w0EQ3nYIZOwJ2J92V2tHFm5jqQxzO//xcZihtzUXHrDVbwPxE9Ao/APnwAJ4ZHtMiBOE0AAAAASUVORK5CYII=",
  #  5.33  Wild Blonde Hair
  "Wild Blonde Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAt0lEQVRIie2VSw7DIAxE7aqbHDcn4bgs3YVbFZshJiCUDSNFJMjw8AeHRYRW6rV09+cBOQnldL1DYBN5wEQUQ9QG2r2r0yAdJ1FOOsYgLu28B/x97Ny1B+xG40krRB7SI0HvFqCuiTPW+VZ46nkTBQvQHIycvpQ5HMqBuO8piAeM9o26MBqAWnFpIkjTg7GQ4ERDwAyou0x/ie5tE2UH8JcOejBSRf9b7IQAqF3cgZi1vP9oGzCtD8XbOs3x+AEwAAAAAElFTkSuQmCC",
  #  5.34  Crazy White Hair
  "Crazy White Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAfElEQVRIie2TSw7AIAhEoen9rzzd1NS0yE9c1UmMG/ExIzIAWqlj6e0bUAHAvawzKUArZAPAGqQyItGtBrA6d9V4IorI7SD7vT/vIQFAj9VoTH3tEKBOxUB9Q6aDGeG106kcysoVUWZERWlTFIW0xlxvMOPAjKhUG/ADwAXl5BcuxbF9jgAAAABJRU5ErkJggg==",
  #  5.35  Wild Hair
  "Wild Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAkUlEQVRIie2UwQrAMAhDk7H//+XsMpmldlZGL6OFHQYxz2qVkrDyHEvd/wkgqfuz/5KhjwWAM9IAEAATpgSSw5cSlciLZ9Mf6iJArSZJfNZk2ZwUetGUqwPchubGonkHGd1geryDBhOuTOkcWPaFldIIo2dqWahgLDxZv/fg4/GgMaC4Ya3mYRD3ut6ADVgPuABhrSc/6K5AGQAAAABJRU5ErkJggg==",
  #  5.36  Frumpy Hair
  "Frumpy Hair" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAaElEQVRIie2TOw7AIAxD/are/8rpwlBVhCBZiKF4Dn44HyJCK3UtdT8AGwAEUJqM6lIAEJJq91YuqbuO+2fg3omdoLUy1T16WxhLSd/fchOUS4DT40+KrpeVYOZzVoIZ7b+DAziAHwAekwsZNIWmNQMAAAAASUVORK5CYII=",
},

###########
#  6) Neck
"Neck" => {
  #  6.0  Ice
  "Ice" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAR0lEQVRIie3NsQ3AMAgF0Ysnw5Pbq1AwBiKVpZQpTPdvgHtPVdHZaL0LECBAgAABAk4eaR7ZA3ikAQuw68BnPoF9Ffg7B3gBAiEWeyL4VgUAAAAASUVORK5CYII=",
  #  6.1  Choker
  "Choker" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAO0lEQVRIie3WsQ0AIAwDQZv9dzYNtBEScvce4K9MnETNrWodAAAAAAAA4M72eNS/gBN3BXiJS5Lbb8sG1y4JMSpu140AAAAASUVORK5CYII=",
  #  6.2  Blue Tie
  "Blue Tie" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAANklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC0YtIAi+ffjwn9Hx7/9vHz7gbfcAAF+XDRXCFACiAAAAAElFTkSuQmCC",
  #  6.3  Hemp
  "Hemp" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC+hmwdODTXhbDRRZADWckSYWEGM4AwMDAwDoGAykbig98AAAAABJRU5ErkJggg==",
  #  6.4  Thick Chain
  "Thick Chain" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC+hmwd+TqnhbDRRZQMhwiixAMpwRnzoAipkL7HbwEpcAAAAASUVORK5CYII=",
  #  6.5  Silver Chain
  "Silver Chain" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRCwaNBSzkanz48CG8OSIvL8+ISx0jrZstAEKFCiuIndFQAAAAAElFTkSuQmCC",
  #  6.6  Medallion
  "Medallion" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAR0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC+hmwd+TqnhbDWRb8PDpXweo4YxUt+Dh078ODAwM+5/I3HAkpBYAmQkR4BsNnk8AAAAASUVORK5CYII=",
  #  6.7  Double Gold Chain
  "Double Gold Chain" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAPElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC2Dg70lVvJU6RRZADWekiQVIhtPMBzDD8foAAHq6De3hKjpKAAAAAElFTkSuQmCC",
  #  6.8  Green Shirt
  "Green Shirt" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAARUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC4a2BYaTpP8bTpLGyafIAsNJ0v9/X/7O8PvydxQ+AwMD1vYPAKKYFasdxu3dAAAAAElFTkSuQmCC",
  #  6.9  Blue Shirt
  "Blue Shirt" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAARUlEQVRIie3WIQ4AIAwDwML//zY9NbdXLBRNAoogSFpX07NtJPEy/em6AAECBAgQIOBvwLxoXsd+BZgXIwcix9IBbP/PBMSDIEnl8zLuAAAAAElFTkSuQmCC",
  #  6.10  White T Shirt
  "White T Shirt" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAL0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC0aOBSwU6EVu7zDiUgQAMXAELySr+pwAAAAASUVORK5CYII=",
  #  6.11  Jumpsuit
  "Jumpsuit" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAARUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC4a2BX9n6v7/O1MXJ58iC/7O1P1/5NZHhiO3PqLwGRgYsLZ/AKZvGmcxVJZSAAAAAElFTkSuQmCC",
  #  6.12  Blue T Shirt
  "Blue T Shirt" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAANUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC0aOBSzkaty44ze8vePvwcqISx0AnyAHL/h5TnIAAAAASUVORK5CYII=",
  #  6.13  Black Tie
  "Black Tie" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMElEQVRIie3WsREAMAzCQMj+O8sb+NK4kwbgWwrksne6LiAgICAgICDwE21Jsv6eAW7ABi3zoDBdAAAAAElFTkSuQmCC",
  #  6.14  Gold Chain
  "Gold Chain" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAOklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC+hmwd+TqnhbDRRZADWckSYWEGM4AwMDAwCLGwvthr3uaQAAAABJRU5ErkJggg==",
  #  6.15  Red Tie
  "Red Tie" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAANklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC0YtIAi+ffjwf5Ki9P9vHz7gbfcAAFGXDKT/B5LuAAAAAElFTkSuQmCC",
  #  6.16  Labcoat
  "Labcoat" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAS0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC+hqwcYdv3G3HP7//08O/g9jb9j+6z8yHx2zkOHg/xt3/Iaz/T1Y8SoGANhQVae1k0CmAAAAAElFTkSuQmCC",
  #  6.17  Purple T Shirt
  "Purple T Shirt" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAANUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC0aOBSzkalzVeRre3gkrN2XEpQ4AmlgHL4MvMrAAAAAASUVORK5CYII=",
  #  6.18  Fast Food
  "Fast Food" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAARUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC4a2BZMUpf9PUpTGyafIgkmK0v8vf/3OcPnrdxQ+AwMD1vYPAHx4FTkX4lYfAAAAAElFTkSuQmCC",
  #  6.19  Grey Shirt
  "Grey Shirt" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAARUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJRC4a2Bc4unv+dXTxx8imywNnF8/+Th3cZnjy8i8JnYGDA2v4BAHJeFO4866ynAAAAAElFTkSuQmCC",
},

###########
#  7) Nose
"Nose" => {
  #  7.0  Clown Nose
  "Clown Nose" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAANUlEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGGoWXGdk+n+dkYnkopfmPmAcrQ9GLRi1gAEAbnQJ26IMLTIAAAAASUVORK5CYII=",
  #  7.1  Gold Ring
  "Gold Ring" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAN0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLUAB/h7UpWk8p0kC6CGM5Kih3G0whm1YPBbAACfrQv+Jty4tgAAAABJRU5ErkJggg==",
},

###########
#  8) Ear
"Ear" => {
  #  8.0  Diamond Helix
  "Diamond Helix" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAO0lEQVRIie3UsQ0AIAACQd79h7RwDBMcwMKKwoQfgOvAtpKN6HqBAgU+AwADOWCuLUnXsdGzK1CgwLsDHVAK7e4PS58AAAAASUVORK5CYII=",
  #  8.1  Diamond Earring
  "Diamond Earring" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAPklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGG4WPHz69z8jIyNG0cxIreIaajiGeVSzABcYOnEwasEItgAAQ8YR6W4lkOcAAAAASUVORK5CYII=",
  #  8.2  Gold Helix
  "Gold Helix" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAO0lEQVRIie3UsQ0AIAACQd5Z3H8OhzLBASysKEz4AbgObCvZiK4XKFDgMwAwkAP2mpJ0HRs9uwIFCrw7hlgKFbSvQesAAAAASUVORK5CYII=",
  #  8.3  Gold Earring
  "Gold Earring" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAPklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGG4W/D2p+p+RkRGjaGakVnENNRzDPKpZgAsMnTgYtWAEWwAAUI0REXrYt/gAAAAASUVORK5CYII=",
},

###########
#  9) Emotion
"Emotion" => {
  #  9.0  Frown
  "Frown" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAMElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IJBbQEjIyPR9SzjaJ084BYAADxqByueLJeXAAAAAElFTkSuQmCC",
  #  9.1  Smile
  "Smile" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAL0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVgWFvAyMhIdC3FOFqjjVpAMQAAQxMHK+pRVS4AAAAASUVORK5CYII=",
},

###########
#  10) Face
"Face" => {
  #  10.0  Purple Eye Shadow
  "Purple Eye Shadow" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAUklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC+hjAQshBRMEsmBlCWPBh2koYgUfpjFSbAEPOwsDAwMD45effzDECOllYGBgYBwt7EYtGLVg1ALCAAD8nRFGvdMXOgAAAABJRU5ErkJggg==",
  #  10.1  Bagner
  "Bagner" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAvElEQVRIie2V0Q3CMAxE7xAD0T3KJHQIhgiDILpH+GeY44sqQomdtM0HEidFVaPUL3YuLiWhpw5dowM4tiyep2FJdwyRJOFVoDqDNPjnXRJIbgd8B2+B7HIGFoReDUu7TzWGWEyhu4v+gB8B5FySzs3TIJJZt62+aJm5rFVNQGlXLdrlDM63Z1+AJQ9gt8qKdS3/A44hAqjrT8tHvZsdJJkDAB6XkwCo9LRiuQAnQ0nC634tAtwSbVV3m74Bk7qjUWhirR4AAAAASUVORK5CYII=",
  #  10.2  Blue Eye Shadow
  "Blue Eye Shadow" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAUklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC+hjAQshBbbhUbCyhPHwymUoYodXLmOk2AIedhYGBgYGxi8//2CIEdLLwMDAwDha2I1aMGrBqAWEAQD6bRFGQUlmDQAAAABJRU5ErkJggg==",
  #  10.3  Horns
  "Horns" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAYUlEQVRIie2SOw6AMAxDHXYfLPc/UBjoBAkNEqgDfkuHWnnKxyICX7JVH06Gk+1CVT4VOBkArF39wABcxlF28BZ3gqfLSfOzDlp7GCNNqQR2emeUeVt2phJIIIEEEvxKsAP/7BDcoPnA2QAAAABJRU5ErkJggg==",
  #  10.4  Green Eye Shadow
  "Green Eye Shadow" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAUklEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC+hjAQshBbFtVrCyhHFx1TEUscVVxxgptkBIWISBgYGB8d3bNxhihPQyMDAwMI4WdqMWjFowagFhAACSmhFoB93e7gAAAABJRU5ErkJggg==",
  #  10.5  Green Eyes
  "Green Eyes" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAANElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0aSBZoT1f5rTlTDECNGL+NoYTdqwagFoxYQBgCaCQrHGOh/VgAAAABJRU5ErkJggg==",
  #  10.6  Blue Eyes
  "Blue Eyes" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAANElEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0aSBZqRG/9rRm7EECNGL+NoYTdqwagFoxYQBgDYEgvAm1O9aAAAAABJRU5ErkJggg==",
  #  10.7  Cleft
  "Cleft" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAL0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVg1IKRaQEjI6MDqRYwjlb6hAAAw2MGbOYsX7YAAAAASUVORK5CYII=",
  #  10.8  Marc Tyson
  "Marc Tyson" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAbElEQVRIie2VOwrAMAxD5dJzJlN7qG45qbqkkC2yS6AFG7QZPfzDRhIrY1vqnoAE/AOwzxLOWp9LtKs1N0CpwLpCJ+9pkUUAICnpKEXOHSVVMMzBHVNAN4+1RwG8MVcBBIDIigKA5cNJwPcBN27BWCqivPEGAAAAAElFTkSuQmCC",
  #  10.9  Spots
  "Spots" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAArElEQVRIic1VQQ7DMAizpz2M/3+KXUq0ZWliSCvVUi8pOGCDQnfHnXjdyv7IC0gaST0+60GQq3nPkSikcfdWvSKXLNFIGkWukkQpo6Plsw+A9XFqrruvJapKE3hrff4iM9rpPchiew9I2jRAMQoDo78N3zL5qLIRjf5dvgcHsa3IW1UVedT80h7MznuU9kAhDiw9aK0mH5o/AsGLYTwA2x5TYO7FJWPad6JK9gGDX0w4TGWKTAAAAABJRU5ErkJggg==",
  #  10.10  Rosy Cheeks
  "Rosy Cheeks" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAO0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLUACm4wMhrfYGTEJmZMFQtwgLPEKmQcrXBGLRj8FgAAIdoK98qfhjwAAAAASUVORK5CYII=",
  #  10.11  Mole
  "Mole" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAL0lEQVRIiWP8//8/Ay0BE01NH7Vg1IJRC0YtGLVgMFjAyMjoS1DNaIUzasHgtwAAzyIGeXSTND4AAAAASUVORK5CYII=",
  #  10.12  Shine
  "Shine" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAANElEQVRIiWP8//8/Ay0BE01NH8wW+BKt8v///+RiX2LUMY5G8qgFoxaMWjBqwagFoxYQAwAokU55NjF/iAAAAABJRU5ErkJggg==",
},

###########
#  11) Type
"Type" => {
  #  11.0  Alien
  "Alien" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA0UlEQVRIiWNMbp32n4GGgIUUxXOrs+Ds5NZp1LVgbnUWw4k/f+B8CxYWoixhIsdwBgYGhhN//qD4iGwLsBlOiiVE+YASgNcCfK6HAUK+GFgfjFpAlAUWLCwMaw4cICiGK6IJWjDnwQOGHhcXvGKzHzzAmZoIWqAjI4ORVNHFdGVkcBYdJMXB5SdPsIpbsOAu0qgWybgKvoFPRchAV0aGZAuIqg+whTGhMookC4g1DBvAG0TJrdPwphB8cjBAUAU+S4jxGVFBhJ4EiaknYIDmyRQABUVYQeaXhCMAAAAASUVORK5CYII=",
  #  11.1  Madlad
  "Madlad" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAABAUlEQVRIicWVUQ6CMAyG/8rCIXgzYbfwNvDkCUh8hcQT8OZh8Br47CEUUx8IywJz6yRiEwKBrl+7ln9UNC3jh6ZinC+no3kumla0ZhcTfOhhLhu2GjAFt00KCQJcwWMg4i361rwAX/aThar4bwWbAJSOex8NGPplMKUR7I0YkOQMZjYQpQFmRpLLFEbUAyIyGU93IjLffZMUBDTX52I7XjdC3T0kubnFbn8oAQB1V6LKUufCKktxvtsQt594TJX2T84ndRXLtXRq5ka+A0ciFcBY2eoK7LG0pyoIlwLmYyk1b5OLpjWNtU8zk51ALoIVjBD3TyTqT9hl2UBp84EN5PoNIttknInHSYYAAAAASUVORK5CYII=",
  #  11.2  Ape
  "Ape" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA8ElEQVRIiWNMbp32n4GGgIUUxXOrs+Ds5NZpROlhIsVwExUBOEa2jGILYIYjA2ItIWgBNsNJsYToICIX4LUAn+thgJAvBtYH1ABE5YMzdz5giBEKOqItCPBxYQjAI79hyx68+gkG0ZNnbxiePHtDUIxsCxzMdBhmrDqAVwxfSiJowZ0nLxhaCkIIiuECVElF2BIByRbUTFiDQjMwoEYwrtKVoAUwQ2BBAqMJpR6iLQjwcSFJHB0QXeEgBw3MF2fufCCY4Yi2gNhUgw7wBlFy6zQUl5MDCPoguXUaQw2OTERMeURUEKEnQWLqCRigeXENAD0AWRDbitIJAAAAAElFTkSuQmCC",
  #  11.3  Devil
  "Devil" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA3UlEQVRIieWVsQ2EMAxFk9OV3oCFYI50NwASujpCYoB0NwcsxAbuuQoUGccxKNEVZymNE/2Hvx1inQ+bqRiP1MY69qfc5/06luZ8ErCOvWmG6SS+GXMsCmmGiYUkK+DE4+AgXGQt4sQ5yCWLYkgLIH5hC5AUTwJi/2dEERDv074lAfvhJSO+x4LIiouAUvEHgA7AdGSSuNxtwIx4ajbNSZdOZRF30bR/yCI9sCUANiPkfGDzTy3g7qNRfUzVFcT2XKnmtxY5H8TGSnsqQAzhlqYqlUV0BKVXjkb1KfoCWgxVRPg87oMAAAAASUVORK5CYII=",
  #  11.4  Gold
  "Gold" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA00lEQVRIiWNMbp32n4GGgIUUxXOrs+Ds5NZp1LVgbnUWw58TKgiNFllEWcJEjuE/JSoZ/pxQQfER2RagG87AwMDA/qKdaEuI8gE2wP6inSh1eC3A5np0QMgXZPuAWDBqAeUWnLz6k+Hk1Z8Exci2wMC5gcE6+TFesa8P5uJMSQQtYH/RjjWjIYvhyxNUiQMWizuUW8BicQevQbgKPqJLU0I5GhegeTIl2gfIwUOKbwY2iJJbp+GNWHxycDWEFEAswZ6JiPEVUUGEngSJqSdggOapCACLpllnUyYuYQAAAABJRU5ErkJggg==",
  #  11.5  Bot
  "Bot" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAwElEQVRIidWVPQ7DIAyFTdWD4ZVrsGVnyswV2HINVnOzdiJqq/qHpBHqk5ASOfKXZ2xwMZcHXKj7yMfbuuzPMZffArZ1ASLa3xHRBLkdSQ4AQERvjg4DviUfgZgcnJEIkP6+S3Mx18FfANQ58N6zsdaaClAdOOfYVWs9D7BI6iS1RCklNhZCUOEqwJIEEdmYuUSIKCbiDj7zaapNNKf5c9D1Wp4RN3NLFHMRN1aKdakOJIjFlalEny1ouSe6Lu+iJyiXRkxD7AI/AAAAAElFTkSuQmCC",
  #  11.6  Zombie
  "Zombie" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA0UlEQVRIiWNMbp32n4GGgIUUxXOrs+Ds5NZp1LVgbnUWQ82CDDi/JSGLKEuYyDGcgYGBoWZBBoqPyLYAm+GkWEKUDygBeC3A53oYIOSLgfXBqAVEWfDgwhuGBxfeEBQj24IlE9YwLJiwBq8YvpREsKioWZDBkHDhDYMCATFcgKg4UDAQwSvWkjCDMgtghuAzCFfBR3RpSihH4wI0T6ZE+wA5eEjxDclBRGz6hwG8QZTcOg0jYolNPTBA0AcQS7BnImKCiqggQk+CxNQTMEDzVAQAeSFXLVtQQrAAAAAASUVORK5CYII=",
  #  11.7  Marc 4
  "Marc 4" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAwElEQVRIiWNMbp32n4GGgIUUxXOrs+Ds5NZp1LVgbnUWw7ruRDg/qDSLKEuYyDGcgYGBYV13IoqPyLYAm+GkWEKUDygBeC3A53oYIOSLgfXBqAVEWXDj7F6GG2f3EhQj2wJFFU2GqhWP8IrhS0kELWDnl8JIqtjEcAGqxEFQ6XzKLQgqnY/XIFwFH9GlKbFBgg5onkyJ9gFy8JDim4ENouTWaXgjFp8cDBD0AcQS7JmIGF8RFUToSZCYegIGaJ6KAKY1TFsp4xthAAAAAElFTkSuQmCC",
  #  11.8  Marc 1
  "Marc 1" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAvklEQVRIiWNMbp32n4GGgIUUxXOrs+Ds5NZp1LVgbnUWw58TcxEaLZKJsoSJHMMZGBgY/pyYi+Ijsi3AZjgplhDlA0oAXgvwuR4GCPliYH0wagFRFtx69JLh1qOXBMXItkBd35RBK6wKrxi+lETQgv/vH2EkVWxiuABV4oDFIplyC1gskvEahKvgI7o0JTZI0AHNkynRPkAOHlJ8M7BBlNw6DW/E4pODqyGkAJ8lxPiKqCBCT4LE1BMwQPNUBADczFaoS3NEEwAAAABJRU5ErkJggg==",
  #  11.9  Marc 3
  "Marc 3" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAxElEQVRIiWNMbp32n4GGgIUUxXOrs+Ds5NZp1LVgbnUWQ6G9HJzfX51FlCVM5BjOwMDAUGgvh+Ijsi3AZjgplhDlA0oAXgvwuR4GCPliYH0wagFRFjx7/ojh2fNHBMXItkBKmINh5S38YvhSEuGigk2ModCeCDEcgCpx0H8Qd3ARbUH/wUd4DcJV8BFdmhLK0bgAzZMp0T5ADh5SfDOwQZTcOg1vxOKTgwGCPkhuncbQjyMTEeMrooIIPQkSU0/AAM1TEQA/Y0UT00Wx4gAAAABJRU5ErkJggg==",
  #  11.10  Marc 2
  "Marc 2" => "iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAvklEQVRIiWNMbp32n4GGgIUUxXOrs+Ds5NZp1LVgbnUWw6ubN+F8MXV1oixhIsdwBgYGhlc3b6L4iGwLsBlOiiVE+YASgNcCfK6HAUK+GFgfjFpAlAW7t2xh2L1lC0Exsi1QUVVliC4uxiuGLyURtEBRXR0jqWITwwWoEgdi6uqUWyCmro7XIFwFH9GlKbFBgg5onkyJ9gFy8JDim4ENouTWaXgjFp8cDBD0AT5LiPEVUUGEngSJqSdggOapCAC521HPVdkUnAAAAABJRU5ErkJggg==",
},
}




def slugify( name )
  name = name.downcase
  name = name.gsub( ' ', '_' )
  name = name.gsub( '/', '-' )
  name
end



attributes.each do |category, h|
   h.each do |name, data|
      puts "==> decoding #{category} / #{name}..."

      img = Image.parse_base64( data )
      img = img.mirror  ## note: flip to right-looking

      name_slug     = slugify( name )
      category_slug = slugify( category )

      img.save( "./tmp/#{category_slug}/#{name_slug}.png")
      img.zoom(8).save( "./tmp/@8x/#{category_slug}--I--#{name_slug}@8x.png")
    end
end


puts "bye"