$LOAD_PATH.unshift( "../../pixelart/pixelart/lib" )
require 'pixelart'

attributes = {

##############
## Heads
 head: {
 'Light 1' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAtklEQVRIiWNgGAXDHjASoeY/JfoJKfh/e2MDTklV/waCZjARYziPlCZWBVB5fD7EawHc8C/PrhNSRr4FlBhOlAWUAhZiFK3fdYqBgYGBIdDNDEOMEMDlA5TUUzZ1G4OHkRiKAmxi2ABRPsCWVPElX2SAMw6gaZxigMsCnJlH1b+BJMuJCiJkQGzQwMDgSKYwgBw0xPqEJAtIDR4GBgqDiJjSlGgf4Eg5BOsDUlMRMRUUCqB5KgIAHCwuITa/cDMAAAAASUVORK5CYII=',
 'Light 2' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAtklEQVRIiWNgGAXDHjASoeY/JfoJKfh/e2MDTklV/waCZjARYziPlCZWBVB5fD7EawHc8C/PrhNSRr4FlBhOlAWUAhZiFLXM2MzAwMDAUJPhiyFGCODyAUrqWbj9LENxiC6KAmxi2ABRPsCWVPElX2SAMw6gaZxigMsCnJlH1b+BJMuJCiJkQGzQwMDgSKYwgBw0xPqEJAtIDR4GBgqDiJjSlGgf4Eg5BOsDUlMRMRUUCqB5KgIAEEcvTXc8NnAAAAAASUVORK5CYII=',

 'Medium 1' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAtklEQVRIiWNgGAXDHjASoeY/JfoJKfi/rjsRp2RQ6XyCZjARYziHiCJWBVB5fD7EawHc8B9v7hNSRr4FlBhOlAWUAhZiFJ04f4eBgYGBwcJQBUOMEMDlA5TU07XsMIOmPB+KAmxi2ABRPsCWVPElX2SAMw6gaZxigMsCnJknqHQ+SZYTFUTIgNiggYHBkUxhADloiPUJSRaQGjwMDBQGETGlKdE+wJFyCNYHpKYiYiooFEDzVAQAUHYtbfcz0SIAAAAASUVORK5CYII=',
 'Medium 2'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAtUlEQVRIiWNgGAXDHjASoeY/JfoJKfi/rjsRp2RQ6XyCZjARYziHiCJWBVB5fD7EawHc8B9v7hNSRr4FlBhOlAWUAhZiFC3efJKBgYGBIdbXHEOMEMDlA5TUs/7QNQY/a9SIxiaGDRDlA2xJFV/yRQY44wCaxikGuCzAmXmCSueTZDlRQYQMiA0aGBgcyRQGkIOGWJ+QZAGpwcPAQGEQEVOaEu0DHCmHYH1AaioipoJCATRPRQB5rC5p549cPAAAAABJRU5ErkJggg==',

  'Dark 1'   => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAtUlEQVRIiWNgGAXDHjASoeY/JfoJKfhfaC+LU7L/4GOCZjARY7iUCD9WBVB5fD7EawHc8GdvPhJSRr4FlBhOlAWUAhZiFD19/piBgYGBQVpSFkOMEMDlA5TUs+oWA4OMICeKAmxi2ACuJIY3eSIDQkkVZxxANVIMcFmA00X9Bx+TZDlRkYwMiA06GBgcyRQGkIOGWJ+QZAGpwcPAQGEQEVOaEu0DHCmHYH1AaioipoJCATRPRQBLiy1Uef9tkwAAAABJRU5ErkJggg==',
  'Dark 2'   => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAtUlEQVRIiWNgGAXDHjASoeY/JfoJKfhfaC+LU7L/4GOCZjARY7iUCD9WBVB5fD7EawHc8GdvPhJSRr4FlBhOlAWUAhZiFJ26/ZiBgYGBwUxVFkOMEMDlA5TUc/QZA4O5LCeKAmxi2ACuJIY3eSIDQkkVZxxANVIMcFmA00X9Bx+TZDlRkYwMiA06GBgcyRQGkIOGWJ+QZAGpwcPAQGEQEVOaEu0DHCmHYH1AaioipoJCATRPRQA6VS3JBLgqewAAAABJRU5ErkJggg==',
},
###########
## Headwear / (Red/White/Brown) Shemaghs

  headwear: {
## -- red shemaghs
'Red Shemagh'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAnElEQVRIie2UwQoCMQxE0+Zbmrv+/zc0d/0WHU8rbpmNG6kHcQdCoC3zGGgicug/BGCzem0AANZ7bc93HwEi8xGSBYSmrKcAWfNeWw4wM0FZAK9yNSx3e3W+X+l5HQ9cDafbJeMdiiWAqxURkQyoFB54TABXk6x5pBXA1aYZr8R+TzTdrPYANtfAFAD537+VgE3oPMC7VXwk+GqCB5POyzSgVCG6AAAAAElFTkSuQmCC',
'Red Shemagh & Agal'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAqUlEQVRIie1UQQ7DIAxLYF8p9+7/b4B795bOu6yTYA6Fih6m1VIUKUJ2TCAiF/4DAMyIbgIAsBzd9Dl3SKBGXor0ClRJWba4dRPIiqo7LdlcJZzlaLPemqtgd3/AAcWtLCQfMK+LRB+6iO7PB62zGSD5oCIi87o0C6jSEXzNAOndeQ95DZlA8mEYcQb2/mu/m0WLgLkGhgiQH/pbDtiOGSewt4ovB6c6eAEZZo6zhsvaXwAAAABJRU5ErkJggg==',
'Red Shemagh & Crown'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAA3klEQVRIie2UsQ6DIBiED+gbdHEx6SJ7H8En9w0kXbvaxE5dunRprosaUKDQaJMm/RJiQP4775cAfAOS04jRNUV8gwfpE+magrwdHLFx7lsfa5IMyvoq5qIh7Pd2XdRg5HJ6xLST93kN5il8bUn5+qDBmggAzukRQnx0WrL/QVn3AIB9fU+ah9g8wW6+QBJG6ck8FbKHEMuSRYuM0jw+zznaURYtAkCjtACAXKOUBBzaky0ewjEwSq8m7GDdpmxlxQHkjncGk3grK7ayWtfAFh+ev5WAmybwiP8TfC/BC9UDQ1RUVVXlAAAAAElFTkSuQmCC',

 ## -- white shemaghs
 'White Shemagh' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAbElEQVRIie2QQQ7AIAgEl6b//zK9NaZZoCp4MM7JBMywCxy2RwBAVb0dbyjvQ4QuXMEBrvnHHPfoR7JLI0QJpikXWBUBRuReWIKe/ocEQNL1TJB6PROkYwnSkrSC9Hq+ghKWCUrqaQVlHEHIAw+SDSQbz7hoAAAAAElFTkSuQmCC',
 'White Shemagh & Agal' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAcklEQVRIie2RQQrAMAgE15L/f9neSiir1qA9hMwpoGFWBQ7bIwCgql6PV5TnIUIbriCAa/5Qx1j9SHrpCFRgjbsCFQQ3oVihrBUBxshZ2JHz8ZMCoCg9E5SmZ4JyLEHZJLOgfD1vQQu/CVrWMwvaOIKQGwRhECvRC0yWAAAAAElFTkSuQmCC',
 'White Shemagh & Gold Agal' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAiklEQVRIie2S0Q2AMAhED+MILuNgTuFgLuMO+KUxeoCN1A/T+2oK9MFRoOn3EgBQVS/HC8pxEKEJXdCAS34QR88uRUQBYJmGqB7jvO4QOkI0wWtZOwhHvz1kLIFa5BWUigEUCH8Wa4jeWztI6Z4Bir0vBaTLAqRNcgak23MFVNFngCr2nAHV1AChNv9TFyvQnEPfAAAAAElFTkSuQmCC',
 'White Shemagh & Stylish Gold Agal' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAk0lEQVRIie2RwQ2AIAxFf40j6DAOpks4mA7jDvWEIaWlkoAHwzsZLbz/K9D5PQQAzJybyX2k54FIHRjVU0QMAMc6eQF52a9EliSQDYLAaRZmswK1QeDcZlfgBgDUpH50eZHxE8wG1oFSNMHr/YtA6vvBmi+6PYMUFO++VFAdS1CtSSyovh4paMJngibriQXN6AKXGy2VHYE1/rxiAAAAAElFTkSuQmCC',
  'White Shemagh & Crown' =>
  'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAsUlEQVRIie2SMQ7CMAxFv7lCly6VuEpO3jNwhiLBxMLCZpYGpaltHOR04kkd0sR+thPgCJj581ks82gfEDhJSZZ5ZH6cN8nyWvqfY1yCKd2pTqpR7pdxpiBzvbys3O5zoqDuQhqLp3pVEAkB2LweIvrptTTfwZRuAIAhPV1rje4d7AQrnPdaINqHSCNqrt5Cu4Pm6r2C0OolQTiaIKyTUhA+nlrQhcMEXcZTCrrxF3zlDe6NXkzwLacCAAAAAElFTkSuQmCC',

  ## -- brown shemaghs
  'Brown Shemagh & Agal' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAmUlEQVRIie2TWxJAMAxFb4yNsA02wIJ1A7oNXUp9eExL2k5QH8b5MkROcwXw83kIAKy1wQKjVfghQFXTLRdEbEERsyeaA4A1WkULyouNOQk7AhsREUkEXq8j7ATTOIi7123P3mcF6wv8VxNyisjJXySQTkAAsK3gHbw1FW6PXODyxOljguQPJBbkiMcT5OIdQa54dkFOfkGSGXvmMfEUVW5uAAAAAElFTkSuQmCC',
  'Brown Shemagh & Crown' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAyklEQVRIie2TsQ7CIBCG/zO+gUuXJvocToy+cDt2aR/AF2iHmujk4uJ2LtIAATwUOvklDFC47ziuwBow8zJizF0V3+Bh4wsydxXzfW8F03Pfuj4jEtTqRm7QEOZ381xUoLmcn7HY4n1egXsLX1kk2QcFOSEAVvcQ0VfdkvwGtboCAHbqIZqHKH4DaIE5xr5JFoR+0q27MA0tA8DYN6kOmeANAcDhePpZYD2yzj4nwS7KkX1MwNPQ5hWUKI8lKMU6glLlWQQl+Qs+8gIjIXwAmZk8FwAAAABJRU5ErkJggg==',
},
################
##  Facial Hair / Beards
 ## -- white beards

 beard: {
 'Normal White Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAaElEQVRIie2SSw6AMAhEp8YE7n9aWNWNNf0oJXWl4S1hMo8FQBAEQfABkrUUkVwyRHSbUVUw82PH7jgiA0iq2gyJCOfsOmJVUEoaeuFbQaG+dJCuCFJX5Cqt2RwZ8xFme4/AKpnJf8ABUW4V7jT70ZsAAAAASUVORK5CYII=',
 'Messy White Beard'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAXElEQVRIie2RSwrAMAhENRT0/qfVlV2UQAIxpptCYR4Igjr+iAAAAIAP4CrBzLobWb2qpvXtcJAuzoNlTSeuF+KZYNDmEicbVGfcxssfRDxDu/vyByJCzKXMj7kBQtwQDHofincAAAAASUVORK5CYII=',
 'Short White Beard'  =>  'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAW0lEQVRIie2SwQoAIQhEbVnQ//9aPbWnwA3WZukUzDsFyrwsRQghhBxAq4ru3nOPqkpEvHrMrBRcwCX6OMzhufbFDQigoF3BID8pJF0J2hT0exLkD6pFKJeEQDz1Vw/7DjytYQAAAABJRU5ErkJggg==',
  'Luxurious White Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAXElEQVRIie2RsQ6AQAhDn8aB//9atrvFQQePNsbBhJcwlVCg0DRN0/yAbSVm5qh6ACLiUduFJcZZrgbAIRhch9k4BnB/l2ToGthXVBmUAVc9SsivUAxWGyoXfssE2vkLFOM3eo0AAAAASUVORK5CYII=',

 ## -- brown beards
 'Normal Brown Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAWklEQVRIiWNgGAWjYBSMglEwBAAjPklnSZb/hNTsff4HrwVMRDjiP5lyDAwMDAwsRFhAlEGUWgADyMFFlKWELGBEM4hknxATB/giGW8CINYCmEHohhE0fHgAAKbWChUO6wJnAAAAAElFTkSuQmCC',
 'Normal Brown Beard & Mustache' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAaklEQVRIiWNgGAWjYBSMglEwBAAjPklnSZb/DAwMjDzCAgwbr7whywImItT8//L2Az4H4AUsRDqEoEGUWsDgLMnC8JSJFc6X/vebKhYwMiC5nlhDkQExcYAvIeBNJMRaADMI3TCChg8PAADd6xC7QG7FfAAAAABJRU5ErkJggg==',
 'Luxurious Brown Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAdElEQVRIie2SQQ7AIAgE14Y+wn6HPrt+pz6iJnoxjRcRDj00YRJPi7sEABzHcZwfECSRI9VVDQCkXKbapmii9mfVAACkCBjNzFgCcN3PO67z2FWBpgCt6Yi4A2l52hoxgCMFySDlAo4kXtnyBDuz0Wj/f0cDpgsatIHnDtkAAAAASUVORK5CYII=',
 'Messy Brown Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAUUlEQVRIiWNgGAWjYBSMglEwCugAGAkpcJZkgTH/49K/9/kfnPqZiHQIzHBGJIzLUhTAQkgBmiHYDPzPgCckiPEBoWDEK09sEOEyhGAcDn0AAAfMCQ8Hbq/AAAAAAElFTkSuQmCC',

  ## -- grey/gray beards
  'Short Grey Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAWElEQVRIie2RMQrAMAwD3dLBz86z5clZGujQuAqZCjoIOAh0YJsJIYT4OwAaABsvM+35B/DZcRKeNoaImGYzLkJAFe0K3kSU9KjCe8dlkbuX+dINFjPB0QFh+SU2GiukKQAAAABJRU5ErkJggg==',

## -- more beards
 'Stylish Mustache' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAASUlEQVRIiWNgGAWjYBSMglEwCgYL+P//PwMDA8N/LJggYCHBHkYNaU64oTeefmckQS9+APUBWYBYV/xnYGBgRLeIkZF6nhjBAACZWRL8XsTmNAAAAABJRU5ErkJggg==',

 'Luxurious Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAV0lEQVRIiWNgGAWjYBSMglEwDMB/Sg1gJMECbGr/45FjYGBgYGAhwTFk+YYUCxgy9Tng7OkXfxClh5QgIsscQhYQYwleM5iIsIAiQIwPGBhw+4JY/bQDAH/ICg2UlJRMAAAAAElFTkSuQmCC',
 'Shadow Beard & Mustache' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAATElEQVRIiWNgGAWjYBSMglEwDIAvpQYwUWgJQQcQYwHMoP9YMEHAQqQFDAwMDH5tEXJwTtWKR0RpYiRCDaFg2EypBfgswWv4KCAKAACQpwuI9rNocQAAAABJRU5ErkJggg==',
 'Normal Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAATklEQVRIiWNgGAWjYBSMglEwDMB/Sg1gIsaS//9x2kPQAYyEDCfCAXjNYCHCADhoi5CDs6tWPCJKDyEfMDAQ9gVeM4ixAJ8lxOofBbgBAHzcDARfx9EJAAAAAElFTkSuQmCC',
 'Sideburns'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAJElEQVRIiWNgGAWjYBSMglEwCgiD/5QawERrS4ixYBSMAvwAAHjSAgOKnbIlAAAAAElFTkSuQmCC',
 'Mustache' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAANUlEQVRIiWNgGAWjYBSMglEwCugAGElQ+58c/URb8P//fwZNGS64JdeffGNkZCTFfaNg2AIAG1wIA3z2UBoAAAAASUVORK5CYII=',
 'Light Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAWklEQVRIiWNgGAWjYBSMglEwBAAjAfn/DAwMjP///8dtACN+I5hIdxNpgCgfILFJ1U9YATLQkOZEtoTxxtPvBPUQG0QwgxmRMLI4ToDXB7DIhUYkWUE0CggCAFKiEAptnzDCAAAAAElFTkSuQmCC',
 'Shadow Beard' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAR0lEQVRIie2PMQ4AIAgDW+P3fC0PxMkVGt1MbyKB9ApgjDHmA9ZrwHiUtAWmWOT6E1UAAMjMODNJSUrhpguKaqkIKkkZbiQ26RMHQWPmna4AAAAASUVORK5CYII=',
 'Sideburns & Mustache' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAARUlEQVRIiWNgGAWjYBSMglEwChgYGAnI/2dgYGD8//8/ds2MhLQTZwFMHTZbCNrAQtAJSIZpSHMiW8J44+l3ErSPgmELAN2tCgjgVOLMAAAAAElFTkSuQmCC',
},
############
## Eyewear
  eyewear: {
  'Horn Rimmed Glasses' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAPElEQVRIiWNgGAWjYBQMfcCIR+4/NcxiIaTr1PN/hTC2mSRTPy4xXICJgIvQXUWsGFEWjIJRMApGARQAAHD5CRC/FaSZAAAAAElFTkSuQmCC',
  'Nerd Glasses' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAQElEQVRIiWNgGAWjYBQMfcBIhJr/WPRgEyPZArghDbdvQWhVNQYcYjjNYcJjASMOjcT4miTFFAXRKBgFo2A4AACcqwsJ54Si9AAAAABJRU5ErkJggg==',
  'Big Purple Shades'    => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAZUlEQVRIiWNgGAWjYBQMfcBIQP4/Dj24xEmy4D8DAwNDJo8rXGD6l91wNhZxrGax4DT9/39GRkbG/8qMYtgchU0cK8BpASMjxEGKIqwIwc8IJi5xbK4hBJDDm5EI8VEwCkYBvQEAMigS3fpBCRkAAAAASUVORK5CYII=',
  'Classic Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAATUlEQVRIiWNgGAWjYBQMfcCIR+4/NcxhIqCJkYGBgSHGkp8hxpIfxTA0MZyAhRjnZduwMjAwMDAsOY5fjBLwnwEzyLCJjYJRMAqGJQAAfgwLxb2GAqQAAAAASUVORK5CYII=',
  'Small Shades'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAL0lEQVRIiWNgGAWjYBSMAoKAkYD8fyqYQZTh/7FYhk0MAzDhkSPbZaNgFIyC4QYAovwGAIP/A58AAAAASUVORK5CYII=',
  'Regular Shades'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAL0lEQVRIiWNgGAWjYBSMAoKAEYf4f2qZhcsCfJYxEhAnC/zHYiA+8VEwCkbBsAIAZRwG/3nqKWUAAAAASUVORK5CYII=',
  '3D Glasses' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAUUlEQVRIiWNgGAWjYBQMfcCIS+LDhw//STFIQEAAq1k4LUC2xGkuL1xsX/JnBgYGBgZeJye42Od9+3BawESOq0gBBA0gNqio4ZhRMApGwWAFAEc1Ejeq220gAAAAAElFTkSuQmCC',
  'VR' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAWElEQVRIiWNgGAWjYBTQHDASoeY/JeYQsuD/woULGZSUlHAquHfvHkN8fDwxZmEavmjRov+HDx/+zwDxBVaMJI8VMOG14T8xoYMf0DyIaB7Jo2AUjAI6AABkXyVwTmw1BAAAAABJRU5ErkJggg==',

  'Big Pixel Shades'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAATklEQVRIie3OywrAIBBDUdP//+frSqjMw3ZVCjkgQsTMjGFm/6fDOyEASQp51dUNyEo6adf19AOw7jSvdAO2EikuWOVvsQ5w33jLzexDE9XdI/GsgjX+AAAAAElFTkSuQmCC',
  'Big Round Shades'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAUUlEQVRIie2RSwoAMQxCde5/Z7sqk5b+sikUfEsjShLAGPM+HImSfgOpMGKd9XqqAIAmOiSxC19mTZt3RadZXyJgGZQyhzsD7RbRf/QDY8wFCtsjEwidCTWDAAAAAElFTkSuQmCC',
  'Classic Green Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAQklEQVRIiWNgGAWjYBQMfcCIR+4/NcxhIqAJojHHFIKRDUMVwwlYiHKfggBxYhSA/wwMDP8ZelwJiY2CUTAKhiUAADNaCY3TvN4hAAAAAElFTkSuQmCC',
  'Regular Reflective Shades'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAASklEQVRIie3NMQ6AMAxDUYdT+f4X+yxUQqgZChOV3xQ5kSNFxP9VtwBUVXztOtrrR7nt8bhm+TJAkpCEbcbc5a8e3MuuwjaPiJ2dNrAt0onoBJkAAAAASUVORK5CYII=',
  'Big Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAARklEQVRIie3NMQ4AIAwCwOL//4yTU0tNJ2PCbdIIEWb2P1zuTAEJAClXXd1AVdIpu5ZsJ8sPKlfkADDqmQ+cHfFWuZm9sAEFNwwMvtjHMQAAAABJRU5ErkJggg==',
  'Big Green Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAW0lEQVRIiWNgGAWjYBQMfcBIQP4/Dj24xEmyAGJIjilCZMppBBtTHKtZLDhN//+fkZGR8T+DECc2R2ETxwpwWsDICHWQFC92BbjEyQD/4XiGNzHio2AUjAJ6AwAtLBRS8+LsIwAAAABJRU5ErkJggg==',

 'Regular Pixel Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAATElEQVRIie2PwQoAIAhDXf//z+tQgYnWoVOwdxHm2NRMCPE/qBYkDQBfs1rpDuEk10SmV5QFPmh+k3lSfTv0UDAM7hNfGvVbkRDiZzpfrCH/gTYLqwAAAABJRU5ErkJggg==',
  'Stylish Nerd Glasses' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAARUlEQVRIiWNgGAWjYBQMfcBIhJr/WPRgEyPZArghn1YXMzAwMDDwhfYy4BDDaQ4THgsYcWgkxtckKaYoiEbBKBgFwwEAAJpbCwl+/AqTAAAAAElFTkSuQmCC',
  'Square Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAPUlEQVRIie3NMQ4AIAxCUfD+d8bR2DS1jkbeiDUfMLP3MRslrQNS4ZmS0r0dABA/d1wFqhgP+2Y0Amb2vQnbuwsGU218pwAAAABJRU5ErkJggg==',
  'Square Reflective Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAARklEQVRIie3QSwoAIAxDwfZWvf/F4lKMFX+rQgbcPEWxZiJSn2cRQD/gDtp2AGm/eRi8ImJq1J/x5bs+OPnWahRfIxKRShoMWyGO08BWQAAAAABJRU5ErkJggg==',
  'Round Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAMklEQVRIiWNgGAWjYBSMHPAfiokVhwNGPAaSCrCahcsCfJYxEhAnC5AdRKNgFIyC4QAAsegK+01gFc0AAAAASUVORK5CYII=',
  'Rimless Glasses'  =>  'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAWElEQVRIie3Qyw2AIBCE4X+NRdiIfUkn9EUjdDGeTLjAmhhv8x33MWQBM7NULHoCQlIeEvOYLXlcq+U39qQfgFpXeQrnERWgdV3DXJ0FTC8YvubbCWb2vxuBDRC+NvhJ3QAAAABJRU5ErkJggg==',
   'Classic Gold Shades' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAQElEQVRIie3OMQ4AIAhD0Y/3Pw+Xc8DVGMXFmGj6xpICICLvs2QWJ/aUTckAqhvVrc/HbCk7cFUAMXw8y0TkSw2vZQ8xGBu/HgAAAABJRU5ErkJggg==',


  'Laser Eyes' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAdElEQVRIie3RyQ1AUBDG8b/tiZO7HjShDr3oTBN60ILlRcaJiC2IwzvM7/hNMksGlFJusJmRN/mW//86LwfYzMhUJIdtr/K98K4pwATEVc5Ag62RqB29pb7kPYkABHVH1I7e0+vWYX2ZytkFZ/knTj9ZKQUzVcU3kjmeWXEAAAAASUVORK5CYII=',
  'MAX BIDDING' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAATklEQVRIiWNgGAWjYBQMDvDsMsN/UsSRARP1nUMieHaZ4f//7zP/o7sWlzhJhsLx//8ohsHloeIwTJFlVPUBNktIEUcGAx/Jo2AUjAAAALCvXiUZVCr/AAAAAElFTkSuQmCC',
},
   mouthprop: {
########################
## Mouth pieces / props
 'Cigarette'  => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAQ0lEQVRIiWNgGAWjYBSMAhRw7969BnQxJlpbOmrBwFtAc8BIgd7/xJhJrgX/jx07hiEoMzWBQW7pLRRzae6DUTDwAADdDQsodjv/MgAAAABJRU5ErkJggg==',
 'Shadowless Cigarette' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAO0lEQVRIiWNgGAWjYBSMAhRw7969BnQxJlpbOmrBwFsw9AEjmfr+Hzt2DENQZmoCg9zSW+SaOQqGKgAAxHkJJmqeTccAAAAASUVORK5CYII=',
 'Bubble Gum' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAXklEQVRIiWNgGAWjYBSMglEwBAAjpQb8b1j1H8XAhjAUMymy4H/Dqv8MYvyogq8+oljCRLHhmW6oEmL8KL4iywIUw6fvwquWLAsYG8IYGV59JGg4AwMd4oDmqWjoAwDWyySle1Ot6wAAAABJRU5ErkJggg==',
 'Vape' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAANElEQVRIiWNgGAWjYBSMglEwCugAGCnQ+58Yc1nINTwyMhJDcPnzZQwMB1DdTHMfjIKBBwApIAcGzyI6egAAAABJRU5ErkJggg==',
 'Shadowless Vape' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAALUlEQVRIiWNgGAWjYBSMglEwCoYDYCRT3//IyEgMweXPlzEwHGAk18xRMFQBAAuwBQIJXf2yAAAAAElFTkSuQmCC',
 'Miswak' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAKUlEQVRIiWNgGAWjYBSMglEwCoYDYCRH0/WV5f9xyWmGd5Jl5igYwgAALL4EAr4+WOkAAAAASUVORK5CYII=',
 'Cigar' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAPklEQVRIiWNgGAWjYBSMAvqDu3fvNiDzmWht4agFAw8YKdD7nxhzWcg13UBODKv4hUevsNtEBiDKB6Ng4AEAaw0IJrHp4okAAAAASUVORK5CYII=',
 'Pearwood Pipe' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAh0lEQVRIie2TQQqAIBBFXx3Fa7QXPIGnEYJu4iUC9x6ioLNMK0OiRZQFhQ8+4iD/MzgDlUql8j4hhD6/N0+Za617gLZkwD/Y/8H3KNmBnHl0dYokOrMPkQPd2gOJztANY/JJoQBb/fIeRGeabhjJO1nmify8TTKPzmzyVgkg3qqyIbm8VaSAFcI9PlqIqn+nAAAAAElFTkSuQmCC',
 'Rosewood Pipe' => 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAf0lEQVRIiWNgGAWjYBSMAvqDXbt2NSDzGWlluJubWwMDAwMDEzUtGB4APQ6GHqCmD/4To4jcVPS/NVAE3ZL/WDBF+eB/a6AIQ/X6NzBzYJYyMDAwwMUpyQeM1evfMCD75PHrLwzINMxmSgGKyx+//sIw48gPuNnUKirQIxxuLgCh0C579GpTowAAAABJRU5ErkJggg==',
}
}


def slugify( name )
   name = name.downcase.gsub( /[^a-zA-Z0-9 _-]/, '' )
   name = name.gsub( /[ ]+/, '_' )
   name
end

attributes.each do |category,h|
  puts "  #{h.size} in #{category}"

  h.each do |name, blob|
    img = Image.parse_base64( blob )
    slug = slugify( name )
    img.save( "./tmp/attributes/#{category}/#{slug}.png" )
    img.zoom(8).save( "./tmp/attributes@8x/#{slug}@8x.png" )
  end
end


puts "bye"

