require 'hoe'
require './lib/cryptopunks/graphql/version.rb'

Hoe.spec 'cryptopunks-graphql' do

  self.version = CryptopunksClient::VERSION

  self.summary = "cryptopunks-graphql - (lite) cryptopunks (http json) graphql api / client"
  self.description = summary

  self.urls    = { home: 'https://github.com/cryptopunksnotdead/cryptopunks' }

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['webclient'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end
